### ISSUE TITLE
Stock-Tools test fails: unit-tests/stock-tools/bindings

### ISSUE THREAD

**Issue by bre1470** [highcharts/highcharts#10387]
```
Uncaught TypeError: Cannot read property 'toString' of undefined
at code/modules/stock-tools.src.js:1561:64

TypeError: Cannot read property 'toString' of undefined
    at H.NavigationBindings.start (code/modules/stock-tools.src.js:1561:64)
    at H.NavigationBindings.bindingsChartClick (code/modules/annotations-advanced.src.js:6285:74)
    at HTMLDivElement.<anonymous> (code/modules/annotations-advanced.src.js:6164:40)
    at Object.triggerEvent (test/test-controller.js:681:25)
    at Object.click (test/test-controller.js:271:18)
    at http://utils.highcharts.local/samples/#test/unit-tests/stock-tools/bindings
    at Array.forEach (<anonymous>)
    at Object.H.(anonymous function) [as each] (code/highcharts.src.js:2359:45)
    at Object.<anonymous> (samples/unit-tests/stock-tools/bindings/demo.js:119:16)
    at runTest (node_modules/qunitjs/qunit/qunit.js:1478:30)

Uncaught TypeError: Cannot read property 'toString' of undefined
    at code/modules/stock-tools.src.js:1561:64

TypeError: Cannot read property 'toString' of undefined
    at H.NavigationBindings.start (code/modules/stock-tools.src.js:1561:64)
    at H.NavigationBindings.bindingsChartClick (code/modules/annotations-advanced.src.js:6285:74)
    at HTMLDivElement.<anonymous> (code/modules/annotations-advanced.src.js:6164:40)
    at Object.triggerEvent (test/test-controller.js:681:25)
    at Object.click (test/test-controller.js:271:18)
    at samples/unit-tests/stock-tools/bindings/demo.js:132:24
    at Array.forEach (<anonymous>)
    at Object.H.(anonymous function) [as each] (code/highcharts.src.js:2359:45)
    at Object.<anonymous> (samples/unit-tests/stock-tools/bindings/demo.js:119:16)
    at runTest (node_modules/qunitjs/qunit/qunit.js:1478:30)
```

**Comment by pawelfus** [comment]
@sebastianbochan
