### ISSUE TITLE
Annotations not IE compatible

### ISSUE THREAD

**Issue by bre1470** [highcharts/highcharts#10392]
```
Object doesn't support property or method 'forEach'
at code/modules/annotations-advanced.src.js:7485:17

TypeError: Object doesn't support property or method 'forEach'
   at H.Popup.prototype.getFields (code/modules/annotations-advanced.src.js:7485:17)
   at Anonymousfunction (code/modules/annotations-advanced.src.js:7452:25)
```
```
Highcharts Touch event test on popup FAILED
        Object doesn't support property or method 'forEach'
        code/modules/annotations-advanced.src.js:7485
                Edit popup is displayed by touch event.
        Expected: -1
        Actual: 17
           at Anonymous function (http://utils.highcharts.local/samples/#test/unit-tests/stock-tools/popup)
           at runTest (node_modules/qunitjs/qunit/qunit.js:1478:6)
           at run (node_modules/qunitjs/qunit/qunit.js:1464:6)
           at Anonymous function (node_modules/qunitjs/qunit/qunit.js:1670:7)
           at advance (node_modules/qunitjs/qunit/qunit.js:1116:6)
```

**Comment by pawelfus** [comment]
@sebastianbochan - it's probably caused by [`nodesList.forEach`](https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach) - not supported in IE

**Comment by bre1470** [comment]
Fixed. Thanks!
