### ISSUE TITLE
Recover from lost webgl context

### ISSUE THREAD

**Issue by manu-st** [highcharts/highcharts#11915]
Hi,

I have the following situation. I started our app using Electron to show a graph on my computer. Then I remoted to my computer where I noticed the following warning in the console:

"WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost"

After that, none of my highcharts graph are showing up, it always fail with:
```
TypeError: Failed to execute 'shaderSource' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLShader'.
    at h (webpack-internal:///1770:13:407)
    at w (webpack-internal:///1770:14:109)
    at eval (webpack-internal:///1770:17:69)
    at Object.init (webpack-internal:///1770:41:207)
    at eval (webpack-internal:///1770:47:40)
    at q.renderCanvas (webpack-internal:///1770:55:102)
    at q.d (webpack-internal:///1770:63:10)
    at q.a.(anonymous function) [as render] (c:\node_modules\highcharts\highcharts.js:20:488)
    at C:\node_modules\highcharts\highcharts.js:289:374
    at Array.forEach (<anonymous>)
```
The line of source code where this happens is:
```
var e = h("#version 100\n#define LN10 2.302585092994046\nprecision highp float;\nattribute vec4 aVertexPosition;\nattribute vec4 aColor;\nvarying highp vec2 position;\nvarying highp vec4 vColor;\nuniform mat4 uPMatrix;\nuniform float pSize;\nuniform float translatedThreshold;\nuniform bool hasThreshold;\nuniform bool skipTranslation;\nuniform float xAxisTrans;\nuniform float xAxisMin;\nuniform float xAxisMinPad;\nuniform float xAxisPointRange;\nuniform float xAxisLen;\nuniform bool  xAxisPostTranslate;\nuniform float xAxisOrdinalSlope;\nuniform float xAxisOrdinalOffset;\nuniform float xAxisPos;\nuniform bool  xAxisCVSCoord;\nuniform bool  xAxisIsLog;\nuniform bool  xAxisReversed;\nuniform float yAxisTrans;\nuniform float yAxisMin;\nuniform float yAxisMinPad;\nuniform float yAxisPointRange;\nuniform float yAxisLen;\nuniform bool  yAxisPostTranslate;\nuniform float yAxisOrdinalSlope;\nuniform float yAxisOrdinalOffset;\nuniform float yAxisPos;\nuniform bool  yAxisCVSCoord;\nuniform bool  yAxisIsLog;\nuniform bool  yAxisReversed;\nuniform bool  isBubble;\nuniform bool  bubbleSizeByArea;\nuniform float bubbleZMin;\nuniform float bubbleZMax;\nuniform float bubbleZThreshold;\nuniform float bubbleMinSize;\nuniform float bubbleMaxSize;\nuniform bool  bubbleSizeAbs;\nuniform bool  isInverted;\nfloat bubbleRadius(){\nfloat value \x3d aVertexPosition.w;\nfloat zMax \x3d bubbleZMax;\nfloat zMin \x3d bubbleZMin;\nfloat radius \x3d 0.0;\nfloat pos \x3d 0.0;\nfloat zRange \x3d zMax - zMin;\nif (bubbleSizeAbs){\nvalue \x3d value - bubbleZThreshold;\nzMax \x3d max(zMax - bubbleZThreshold, zMin - bubbleZThreshold);\nzMin \x3d 0.0;\n}\nif (value \x3c zMin){\nradius \x3d bubbleZMin / 2.0 - 1.0;\n} else {\npos \x3d zRange \x3e 0.0 ? (value - zMin) / zRange : 0.5;\nif (bubbleSizeByArea \x26\x26 pos \x3e 0.0){\npos \x3d sqrt(pos);\n}\nradius \x3d ceil(bubbleMinSize + pos * (bubbleMaxSize - bubbleMinSize)) / 2.0;\n}\nreturn radius * 2.0;\n}\nfloat translate(float val,\nfloat pointPlacement,\nfloat localA,\nfloat localMin,\nfloat minPixelPadding,\nfloat pointRange,\nfloat len,\nbool  cvsCoord,\nbool  isLog,\nbool  reversed\n){\nfloat sign \x3d 1.0;\nfloat cvsOffset \x3d 0.0;\nif (cvsCoord) {\nsign *\x3d -1.0;\ncvsOffset \x3d len;\n}\nif (isLog) {\nval \x3d log(val) / LN10;\n}\nif (reversed) {\nsign *\x3d -1.0;\ncvsOffset -\x3d sign * len;\n}\nreturn sign * (val - localMin) * localA + cvsOffset + \n(sign * minPixelPadding);\n}\nfloat xToPixels(float value) {\nif (skipTranslation){\nreturn value;// + xAxisPos;\n}\nreturn translate(value, 0.0, xAxisTrans, xAxisMin, xAxisMinPad, xAxisPointRange, xAxisLen, xAxisCVSCoord, xAxisIsLog, xAxisReversed);// + xAxisPos;\n}\nfloat yToPixels(float value, float checkTreshold) {\nfloat v;\nif (skipTranslation){\nv \x3d value;// + yAxisPos;\n} else {\nv \x3d translate(value, 0.0, yAxisTrans, yAxisMin, yAxisMinPad, yAxisPointRange, yAxisLen, yAxisCVSCoord, yAxisIsLog, yAxisReversed);// + yAxisPos;\nif (v \x3e yAxisLen) {\nv \x3d yAxisLen;\n}\n}\nif (checkTreshold \x3e 0.0 \x26\x26 hasThreshold) {\nv \x3d min(v, translatedThreshold);\n}\nreturn v;\n}\nvoid main(void) {\nif (isBubble){\ngl_PointSize \x3d bubbleRadius();\n} else {\ngl_PointSize \x3d pSize;\n}\nvColor \x3d aColor;\nif (skipTranslation \x26\x26 isInverted) {\ngl_Position \x3d uPMatrix * vec4(aVertexPosition.y + yAxisPos, aVertexPosition.x + xAxisPos, 0.0, 1.0);\n} else if (isInverted) {\ngl_Position \x3d uPMatrix * vec4(yToPixels(aVertexPosition.y, aVertexPosition.z) + yAxisPos, xToPixels(aVertexPosition.x) + xAxisPos, 0.0, 1.0);\n} else {\ngl_Position \x3d uPMatrix * vec4(xToPixels(aVertexPosition.x) + xAxisPos, yToPixels(aVertexPosition.y, aVertexPosition.z) + yAxisPos, 0.0, 1.0);\n}\n}", "vertex")
````
#### Expected behaviour
It should continue to work properly.

#### Actual behaviour
Graphs are not shown due to the error.

#### Live demo with steps to reproduce
I could not reproduce it with Chrome. Happens in Electron (see above).

#### Product version
7.1.1

#### Affected browser(s)
Electron 2.0.8

**Comment by sebastianbochan** [comment]
Hi @manu-st,
Thank you for reporting the problem. We will try to reproduce it and will let you know about details. 

FYI @cvasseng

**Comment by cvasseng** [comment]
Hi @manu-st, this seems like an issue with Electron. The error you're getting seem to be caused by an invalid WebGL context (which causes the shader compilation to fail). It looks, from the error you're getting, like the WebGL context is lost when switching to a remote session. Are you remoting in to a desktop with your app already running, and if not, are you getting the error when starting the electron app in the remote session?

**Comment by manu-st** [comment]
Sorry for the delay. I am remoting to a desktop when my app is already running. However I was not able to consistently reproduce this crash as I've been trying to reproduce the past few days. What I observed though my explain why we lost the context.

1 - Start the application locally, the remoting in. When it doesn't crash the graphs are definitely using WebGL and boost.
2 - Start the application after remoting in. The application starts properly but WebGL is missing, so we disable boost.

It is strange that by default under remoting WebGL is always disabled but that if you start the app with WebGL enabled, it continues to use it fine.

**Comment by manu-st** [comment]
I've been experiencing this on a regular basis now but in a completely different context. I start my application locally and eventually the content of the electron window goes black and then it shows again but my graphs don't show.

In the console, I can see this warning:
```WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost```
and then 
```Uncaught TypeError: Failed to execute 'shaderSource' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLShader'.
    at h (webpack-internal:///1786:13:407)
    at w (webpack-internal:///1786:14:109)
    at eval (webpack-internal:///1786:17:69)
    at Object.init (webpack-internal:///1786:41:207)
    at eval (webpack-internal:///1786:47:40)
    at q.renderCanvas (webpack-internal:///1786:55:102)
    at q.d (webpack-internal:///1786:63:10)
    at q.a.(anonymous function) [as render] (C:\Dev\\client\node_modules\highcharts\highcharts.js:20:488)
    at C:\Dev\client\node_modules\highcharts\highcharts.js:289:374
    at Array.forEach (<anonymous>)
```
