### ISSUE TITLE
PackedBubble - Cannot Read Property 'pos' of undefined

### ISSUE THREAD

**Issue by hartbert95** [highcharts/highcharts#12287]
#### Expected behaviour
No error in the console when mouse hover to the bubble

#### Actual behaviour
When Hover to the bubble, the error produced.

ERROR TypeError: Cannot read property 'pos' of undefined
    at d.searchPoint (highcharts.js:357)
    at d.eval (boost.js:120)
    at d.b.<computed> (highcharts.js:20)
    at eval (highcharts.js:219)
    at Array.forEach (<anonymous>)
    at c.Pointer.findNearestKDPoint (highcharts.js:218)
    at c.Pointer.getHoverData (highcharts.js:220)
    at c.Pointer.runPointActions (highcharts.js:221)
    at c.Pointer.onContainerMouseMove (highcharts.js:232)
    at HTMLDivElement.b.onmousemove [as __zone_symbol__ON_PROPERTYmousemove] (highcharts.js:234)

#### Live demo with steps to reproduce
https://stackblitz.com/edit/highchart-angular-chart-lkzbho?file=app/views/catalog/catalog.component.ts

1. Click Catalog menu
2. Click Render Chart
3. Mouse Hover to Chart and View Console
4. Error produced

#### Product version
"highcharts": "^7.2.0",

**Comment by hartbert95** [comment]
Hi, @pawelfus, It's worked, thanks for your rapid responses. :D. Will the bug fixed on next release?

**Comment by pawelfus** [comment]
You're welcome! 

> Will the bug fixed on next release?

I hope so :)

**Comment by drice89** [comment]
FYI this happened again - It seemed specific to the "Sunburst" graph type. I implemented the suggested solution above and it worked

```
Uncaught TypeError: Cannot read properties of undefined (reading 'pos')
    at L.searchPoint (highcharts.js:432:377)
    at highcharts.js:287:113
    at Array.forEach (<anonymous>)
    at b.findNearestKDPoint (highcharts.js:287:14)
    at b.getHoverData (highcharts.js:289:500)
    at b.runPointActions (highcharts.js:302:82)
    at b.onContainerMouseMove (highcharts.js:295:23)
searchPoint @ highcharts.js:432
(anonymous) @ highcharts.js:287
findNearestKDPoint @ highcharts.js:287
getHoverData @ highcharts.js:289
runPointActions @ highcharts.js:302
onContainerMouseMove @ highcharts.js:295
```

[Link to video reproduction](https://imgur.com/a/yAUtlI8)



#### Product version
Highcharts 11.1.0

**Comment by bm64** [comment]
Hello @drice89 and thanks for reporting the issue.

Looks like it worked fine in 10.3.3 and was broken in v11.0.0: https://jsfiddle.net/BlackLabel/crgbhe5u/

_Internal note_
Bisected to c2d6c1e8491f59e13b83d5a9550c44c6e7333dd6 FYI @hubertkozik

**Comment by manfromanotherland** [comment]
Also happens on `pie` charts. Setting `tooltip.shared` to `false` fixed the issue for me.
