### ISSUE TITLE
Highcharts source map line numbers are not correct

### ISSUE THREAD

**Issue by jamescrowley** [highcharts/highcharts#13598]
#### Expected behaviour
When an unexpected exception occurs within the Highcharts library, the source maps should allow you to see where the problem is.

#### Actual behaviour
The source map line mappings do not work - they report incorrect line numbers. See below - in v8.1.0 line 40269 is within a block comment.

```
TypeError: Cannot read property 'forEach' of undefined
      at forEach (node_modules/highcharts/highcharts.src.js:40269:21)
          at Array.forEach (<anonymous>)
      at d.Chart.call (node_modules/highcharts/highcharts.src.js:40265:13)
      at node_modules/highcharts/highcharts.src.js:2423:29
      at fireEvent (node_modules/highcharts/highcharts.src.js:2428:17)
      at d.Chart.onload (node_modules/highcharts/highcharts.src.js:26823:17)
      at d.Chart.firstRender (node_modules/highcharts/highcharts.src.js:26797:21)
      at d.Chart.call (node_modules/highcharts/highcharts.src.js:25152:21)
      at fireEvent (node_modules/highcharts/highcharts.src.js:2432:17)
      at d.Chart.init (node_modules/highcharts/highcharts.src.js:25017:17)
      at d.Chart.apply [as getArgs] (node_modules/highcharts/highcharts.src.js:24991:17)
      at new d.Chart (node_modules/highcharts/highcharts.src.js:24930:13)
      at Object.d.chart (node_modules/highcharts/highcharts.src.js:24964:20)
      at t (node_modules/highcharts-react-official/dist/webpack:/src/HighchartsReact.js:39:24)
      at node_modules/highcharts-react-official/dist/webpack:/src/HighchartsReact.js:72:30
      at commitHookEffectListMount (node_modules/react-dom/cjs/react-dom.development.js:19731:26)
      at commitLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:19787:9)
      at commitLayoutEffects (node_modules/react-dom/cjs/react-dom.development.js:22803:7)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:188:14)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:237:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:292:31)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:22541:9)
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:653:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11039:10)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:22381:3)
      at finishSyncRender (node_modules/react-dom/cjs/react-dom.development.js:21807:3)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:21793:7)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21188:7)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:24373:3)
      at node_modules/react-dom/cjs/react-dom.development.js:24758:7
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:21903:12)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:24757:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:24840:10)
      at node_modules/@testing-library/react/dist/pure.js:86:25
      at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:21856:12)
      at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:929:14)
      at render (node_modules/@testing-library/react/dist/pure.js:82:26)
      at customRender (src/testing/index.tsx:43:10)

```

#### Live demo with steps to reproduce

https://codesandbox.io/s/lingering-fast-vpjvt?file=/src/app.test.js has the reproduction, though you're better off running locally to test the source map experience.

#### Product version

8.1.0

**Comment by sebastianbochan** [comment]
Hi @jamescrowley,
Thank you for reporting. When I run the demo I see the blank screen and I am not able to observe your issue in the console (TypeError). Could you verify if the sandbox is correct?

**Comment by jamescrowley** [comment]
@sebastianbochan you need to switch to the 'tests' tab rather than 'browser' view in the sandbox on the RHS :)

**Comment by KacperMadej** [comment]
How are you verifying the correctness of the line number?
If shows correctly for me:
![40269](https://user-images.githubusercontent.com/8960408/83246059-e14dcb80-a1a1-11ea-97c3-c76d9ad8aa06.jpg)
 (and error is from running `forEach` trying to run on `undefined`, so this is correct place in code - I have provided more info about the source of the error in #13599)

In general, minified files and their maps are cool but limited. If you want to have named-as-shown variables in debugged scopes or step line by line without unexpected jumps when debugging and dynamically check and calculate values through highlighting code parts then you should use .src.js version of Highcharts library files (at least in the latest Chrome).

**Comment by jamescrowley** [comment]
@KacperMadej I was looking at highcharts.src.js included in the NPM package. My 8.1.0 version looks like this: 

<img width="859" alt="Screenshot 2020-06-01 at 13 53 08" src="https://user-images.githubusercontent.com/509533/83374550-49551980-a40f-11ea-9241-672f29bd31c3.png">

**Comment by KacperMadej** [comment]
@jamescrowley 
Looks like there are differences between the files. We will be investigating the problem and for now, as a workaround, you could use the code available through [download](https://www.highcharts.com/blog/download/) or our [CDN](http://code.highcharts.com/highcharts.src.js).

_Internal note:_ @TorsteinHonsi 
The `highcharts.src.js` are not identical when comparing 1 vs 2:
1. the code available for download from the Highcharts download web site or the code from CDN
2. the code in `highcharts-dist` repo or the code in the Node package (downloadable via NPM)

The noticeable differences are
- the code lines length limits
- variables in new lines vs no line break between them and separated only with a comma

**Comment by TorsteinHonsi** [comment]
I'm putting this in the backlog, so someone can investigate where the differences come from. FYI @bre1470

**Comment by bre1470** [comment]
Interesting discover is that the source map for the compressed file (without the `.src.` part) works for me.

**Comment by goransle** [comment]
Closing this as #13808 solves the issue for future releases.

Suggested workaround for development: import `src.js`-files directly, e.g. `import Highcharts from 'highcharts/highcharts.src.js'` instead of `import Highcharts from 'highcharts'`
