### ISSUE TITLE
Highcharts exception when running within Jest with Boost enabled

### ISSUE THREAD

**Issue by jamescrowley** [highcharts/highcharts#13599]
#### Expected behaviour

I'm running some Jest tests that have Highcharts in the UI, with Boost enabled. This results in an exception deep in the Highcharts code base. Unfortunately I can't easily figure out exactly where due to https://github.com/highcharts/highcharts/issues/13598. It would be great to be able to workaround this without having to modify the highcharts config specifically for tests.

#### Actual behaviour

```
TypeError: Cannot read property 'forEach' of undefined.

 at forEach (node_modules/highcharts/highcharts.src.js:40269:21)
          at Array.forEach (<anonymous>)
      at d.Chart.call (node_modules/highcharts/highcharts.src.js:40265:13)
      at node_modules/highcharts/highcharts.src.js:2423:29
      at fireEvent (node_modules/highcharts/highcharts.src.js:2428:17)
      at d.Chart.onload (node_modules/highcharts/highcharts.src.js:26823:17)
      at d.Chart.firstRender (node_modules/highcharts/highcharts.src.js:26797:21)
      at d.Chart.call (node_modules/highcharts/highcharts.src.js:25152:21)
      at fireEvent (node_modules/highcharts/highcharts.src.js:2432:17)
      at d.Chart.init (node_modules/highcharts/highcharts.src.js:25017:17)
      at d.Chart.apply [as getArgs] (node_modules/highcharts/highcharts.src.js:24991:17)
      at new d.Chart (node_modules/highcharts/highcharts.src.js:24930:13)
      at Object.d.chart (node_modules/highcharts/highcharts.src.js:24964:20)
```

#### Live demo with steps to reproduce

https://codesandbox.io/s/lingering-fast-vpjvt?file=/src/app.test.js:348-402

#### Product version

8.1.0

**Comment by sebastianbochan** [comment]
Hi @jamescrowley,
Thank you for reporting. When I run the demo I see the blank screen and I am not able to observe your issue in the console (TypeError). Could you verify if the sandbox is correct?

**Comment by jamescrowley** [comment]
@sebastianbochan you need to switch to the 'tests' tab rather than 'browser' view in the sandbox on the RHS :)

**Comment by KacperMadej** [comment]
There is an error in console `Highcharts error #26: www.highcharts.com/errors/26/`.
The environment that you are using has `window` without `WebGLRenderingContext` and because of this, the boost module is not working correctly. Maybe this is some limitation of the sandbox or jsdom. You could try adding the fallback module suggested in the error message, or investigating the source of the limitation, but the issue doesn't look like a Highcharts bug to me (the error is there, so if something fails after an error then it is expected). I have debugged the demo and noticed the error, so if you are not getting the mentioned Highcharts error in conse then it might have been cleared by the sandbox.

**Comment by jamescrowley** [comment]
@KacperMadej I've seen the warning before using jsdom (pretty sure WebGL wont be supported as it's not really a browser) - However, in those previous instances Highcharts had never thrown javascript exceptions deep in its codebase as a result, which made me think it was something else.

**Comment by jamescrowley** [comment]
For the future reference of anyone else that comes here - I've worked around it by just disabling boost when we're inside a testing environment by checking the NODE_ENV variable.

**Comment by KacperMadej** [comment]
@jamescrowley 
Should I mark this issue a feature requests about adding jsdom support?

**Comment by jamescrowley** [comment]
@KacperMadej I wouldn't need jsdom support as such - just for Highcharts to avoid this exception and still do something sensible, if possible!

**Comment by KacperMadej** [comment]
Throwing an error in the console seems to be a very sensible thing to do IMO, so what could be done to make this better?

You could load additional fallback boost module for browsers/environments that don't support the features required by the boost module - the info is on the error page linked here: www.highcharts.com/errors/26/

If the errors are cleared from the browser you could use the debugger module and get the errors to show up in the chart - https://www.highcharts.com/docs/advanced-chart-features/debugger-mode

**Comment by jamescrowley** [comment]
@KacperMadej The uncaught foreach exception (rather than the error logged in the console), is the bit that's inconsistent with the usual behaviour, no?

**Comment by KacperMadej** [comment]
For me, it is not unusual and not the best end for this edge case, but that's just my opinion. At first, you get the error, and later the problem continues and is causing the chart to crash the chart through the uncaught exception. There are a lot of variables and requirements (on system, settings, and browser levels) that might limit or cause problems for the boost module and this issue is happening in the environment that is not supported. I am not sure how to resolve or label this issue, so if you have any suggestions please share.

**Comment by jamescrowley** [comment]
@KacperMadej I have no problem with the ticket just being closed as 'wont fix' - at least the issue is here for reference if others encounter, with the workaround of disabling boost when `NODE_ENV === "test"`
