### ISSUE TITLE
Running getBoundingClientRect on a disconnected node in IE11 throws an error

### ISSUE THREAD

**Issue by natalan** [highcharts/highcharts#13929]
#### Expected behaviour
IE11 Should not throw an error

#### Actual behaviour
Running getBoundingClientRect on a disconnected node in IE11 throws an error.

```
Error: Unspecified error.
  at width(./node_modules/highcharts/es-modules/parts/Utilities.js:1810:13)
  at chart(./node_modules/highcharts/es-modules/parts/Chart.js:1234:44)
  at Anonymous function(./node_modules/highcharts/es-modules/parts/Chart.js:1276:21)
```

#### Product version
Highcharts 8 and below

#### Affected browser(s)
IE11

**Comment by pawelfus** [comment]
Hi @natalan 

Thank you for reporting, but could you provide live demo of the issue? We will check it. Thanks!
