### ISSUE TITLE
Error exporting pdf with UTF-8 characters (custom TTF). Update jsPDF dependency and compatibility with Highcharts.

### ISSUE THREAD

**Issue by roychowdhuryrohit-dev** [highcharts/highcharts#15191]
### **Safari**
```
[Error] Error in function btoa@[native code]: The string contains invalid characters.
InvalidCharacterError: The string contains invalid characters.
btoa
Ft — jspdf.js:31:24330
(anonymous function) — jspdf.js:31:25312
(anonymous function) — offline-exporting.src.js:343
o — offline-exporting.src.js:424
l — offline-exporting.src.js:460
(anonymous function) — offline-exporting.src.js:680
(anonymous function) — offline-exporting.src.js:576
(anonymous function) — offline-exporting.src.js:738
onclick — offline-exporting.src.js:771
onclick — exporting.src.js:1846
	(anonymous function) (jspdf.js:31:25522)
	(anonymous function) (2.aa075033.chunk.js:2:826425)
	o (2.aa075033.chunk.js:2:826443)
	l (2.aa075033.chunk.js:2:826935)
	(anonymous function) (2.aa075033.chunk.js:2:829504)
	(anonymous function) (2.aa075033.chunk.js:2:828179)
	(anonymous function) (2.aa075033.chunk.js:2:829367)
	onclick (2.aa075033.chunk.js:2:830045)
	onclick (2.aa075033.chunk.js:2:685458)
```

### **Chrome**
```
Error in function Object.Ft (https://code.highcharts.com/9.0.0/lib/jspdf.js:31:22686): Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range. DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at Object.Ft (https://code.highcharts.com/9.0.0/lib/jspdf.js:31:22686)
    at Object.Gt.foo [as output] (https://code.highcharts.com/9.0.0/lib/jspdf.js:31:23667)
    at http://localhost:49409/static/js/2.aa075033.chunk.js:2:826418
    at o (http://localhost:49409/static/js/2.aa075033.chunk.js:2:826442)
    at l (http://localhost:49409/static/js/2.aa075033.chunk.js:2:826933)
    at http://localhost:49409/static/js/2.aa075033.chunk.js:2:829502
    at t.getSVGForLocalExport (http://localhost:49409/static/js/2.aa075033.chunk.js:2:828177)
    at t.exportChartLocal (http://localhost:49409/static/js/2.aa075033.chunk.js:2:829346)
    at t.onclick (http://localhost:49409/static/js/2.aa075033.chunk.js:2:830028)
    at HTMLLIElement.onclick (http://localhost:49409/static/js/2.aa075033.chunk.js:2:685452)
```

This issue seems to have been fixed in the latest versions of [jsPDF](https://github.com/MrRio/jsPDF) --> https://github.com/MrRio/jsPDF/issues/2236.

I have previously tried to load the latest version of jspdf but Highcharts is absolutely incompatible with it. It only seems to work with the very old jspdf version hosted at [libURL](https://code.highcharts.com/9.0.1/lib/jspdf.js).

**Comment by KacperMadej** [comment]
Hi @roychowdhuryrohit-dev 

I am unable to recreate the problem - please add a minimal live demo.

From the code errors, it looks like you are using offline-exporting module for client-side export and you have not mentioned this in the bug report so I am mentioning this here as a side note.

**Comment by roychowdhuryrohit-dev** [comment]
Hi @KacperMadej 

I'm getting the following error now on exporting PDF.
```
[Error] Not allowed to navigate top frame to data URL 'data:application/pdf;filename=generated.pdf;base64,JVBERi0xLjMKJbrfrOAKMyAwIG9iago8PC9UeXBlIC9QYWdlCi9QYXJlbnQgMSAwIFIKL1Jlc291cmNlcyAyIDAgUgovTWVkaWFCb3ggWzAgMCAxMjgwLiA1NDAuXQovQ29udGVudHMgNCAwIFIKPj4KZW5kb2JqCjQgMCBvYmoKPDwvTGVuZ3RoIDU4MDMxPj4Kc3RyZWFtCjAuMjAwMDI1IHcKMCBHCnEKMS4gMC4gMC4gLTEuIDAuIDU0MC4gY20KL0YxIDE2IFRmCnEKMS4gMC4gMC4gMS4gMC4gMC4gY20KMS4wMCB3CjAuMDAgZwovRjkgMTYgVGYKL0Y5IDE2IFRmCnEKL0YxNSAxNiBUZgovRjE1IDEyIFRmCnEKUQpxCi9HUzEgZ3MKNS4wMCB3CjAuMDAgRwoxLiAwLiAwLiAxLiAxLiAxLiBjbQo0LiA0LiBtCjEy...AwMjAgMDAwMDAgbiAKMDAwMDA5MjQxNyAwMDAwMCBuIAowMDAwMDkzMzA1IDAwMDAwIG4gCjAwMDAwOTM1MDQgMDAwMDAgbiAKMDAwMDA5NDA5NCAwMDAwMCBuIAowMDAwMDk0MjM4IDAwMDAwIG4gCjAwMDAwOTQyNjkgMDAwMDAgbiAKMDAwMDA5NDMwMCAwMDAwMCBuIAowMDAwMDk0MzMxIDAwMDAwIG4gCjAwMDAwOTQ2NjIgMDAwMDAgbiAKMDAwMDA5NTEzNiAwMDAwMCBuIAowMDAwMDk1MjIyIDAwMDAwIG4gCnRyYWlsZXIKPDwKL1NpemUgMzEKL1Jvb3QgMzAgMCBSCi9JbmZvIDI5IDAgUgovSUQgWyA8M0VDRDZEMUJBNDcyREY2QUFGNjcyRUQ0MzA2NkE1REE+IDwzRUNENkQxQkE0NzJERjZBQUY2NzJFRDQzMDY2QTVEQT4gXQo+PgpzdGFydHhyZWYKOTUzMjYKJSVFT0Y='.
```

This error is only happening in iOS (latest) Safari (latest).

One solution is to add an iframe block to the dataURL --> [Solution link](https://ourcodeworld.com/articles/read/682/what-does-the-not-allowed-to-navigate-top-frame-to-data-url-javascript-exception-means-in-google-chrome)

Can you help me in finding the correct file in Highcharts library where I need to make this change?

**Comment by KacperMadej** [comment]
@roychowdhuryrohit-dev 
As soon as I will have a live demo for the issue someone with iOS will be able to test the problem and look for a solution or a workaround for you. Could you create a demo for the problem that could be tested? If creating a live demo is a problem please let me know more about it.

**Comment by roychowdhuryrohit-dev** [comment]
Hi @KacperMadej 
Unfortunately I can't replicate the exact error on jsFiddle although it was showing me different error on downloading the PDF. 
[Demo #1](https://jsfiddle.net/5s9p2n8m/7/)

```
[Error] Failed to load resource: Frame load interrupted (data:application/pdf;filename=generated.pdf;base64,JVB…U9G, line 0)
```

But you can find the actual error in the console which I am currently facing at this link.
[Demo #2](http://uniris.one/market)  
I am not able to export any graph in PDF format.

This error is only happening on iOS (latest) Safari (latest).

**Comment by roychowdhuryrohit-dev** [comment]
Hi @KacperMadej 
Unfortunately I can't replicate the exact error on jsFiddle although it is showing me a different error on downloading the PDF. 
[Demo #1](https://jsfiddle.net/5s9p2n8m/7/)

```
[Error] Failed to load resource: Frame load interrupted (data:application/pdf;filename=generated.pdf;base64,JVB…U9G, line 0)
```

### Original error: 

I am not able to export any graph in PDF format.

```
[Error] Not allowed to navigate top frame to data URL 'data:application/pdf;filename=generated.pdf;base64,JVBERi0xLjMKJbrfrOAKMyAwIG9iago8PC9UeXBlIC9QYWdlCi9QYXJlbnQgMSAwIFIKL1Jlc291cmNlcyAyIDAgUgovTWVkaWFCb3ggWzAgMCAxMjgwLiA1NDAuXQovQ29udGVudHMgNCAwIFIKPj4KZW5kb2JqCjQgMCBvYmoKPDwvTGVuZ3RoIDU4MDMxPj4Kc3RyZWFtCjAuMjAwMDI1IHcKMCBHCnEKMS4gMC4gMC4gLTEuIDAuIDU0MC4gY20KL0YxIDE2IFRmCnEKMS4gMC4gMC4gMS4gMC4gMC4gY20KMS4wMCB3CjAuMDAgZwovRjkgMTYgVGYKL0Y5IDE2IFRmCnEKL0YxNSAxNiBUZgovRjE1IDEyIFRmCnEKUQpxCi9HUzEgZ3MKNS4wMCB3CjAuMDAgRwoxLiAwLiAwLiAxLiAxLiAxLiBjbQo0LiA0LiBtCjEy...AwMjAgMDAwMDAgbiAKMDAwMDA5MjQxNyAwMDAwMCBuIAowMDAwMDkzMzA1IDAwMDAwIG4gCjAwMDAwOTM1MDQgMDAwMDAgbiAKMDAwMDA5NDA5NCAwMDAwMCBuIAowMDAwMDk0MjM4IDAwMDAwIG4gCjAwMDAwOTQyNjkgMDAwMDAgbiAKMDAwMDA5NDMwMCAwMDAwMCBuIAowMDAwMDk0MzMxIDAwMDAwIG4gCjAwMDAwOTQ2NjIgMDAwMDAgbiAKMDAwMDA5NTEzNiAwMDAwMCBuIAowMDAwMDk1MjIyIDAwMDAwIG4gCnRyYWlsZXIKPDwKL1NpemUgMzEKL1Jvb3QgMzAgMCBSCi9JbmZvIDI5IDAgUgovSUQgWyA8M0VDRDZEMUJBNDcyREY2QUFGNjcyRUQ0MzA2NkE1REE+IDwzRUNENkQxQkE0NzJERjZBQUY2NzJFRDQzMDY2QTVEQT4gXQo+PgpzdGFydHhyZWYKOTUzMjYKJSVFT0Y='.
```

This error is only happening on iOS (latest) Safari (latest).

One solution is to add an iframe block to the dataURL while calling doc.write() --> [Solution link](https://ourcodeworld.com/articles/read/682/what-does-the-not-allowed-to-navigate-top-frame-to-data-url-javascript-exception-means-in-google-chrome)

Can you help me in finding the correct file in Highcharts library where I need to make this change?

**Comment by roychowdhuryrohit-dev** [comment]
Hi @KacperMadej 
Unfortunately I can't replicate the exact error on jsFiddle although it is showing me a different console error on downloading the PDF. 
[Demo #1](https://jsfiddle.net/5s9p2n8m/7/)

```
[Error] Failed to load resource: Frame load interrupted (data:application/pdf;filename=generated.pdf;base64,JVB…U9G, line 0)
```

### Original error: 

I am not able to export any graph in PDF format.

```
[Error] Not allowed to navigate top frame to data URL 'data:application/pdf;filename=generated.pdf;base64,JVBERi0xLjMKJbrfrOAKMyAwIG9iago8PC9UeXBlIC9QYWdlCi9QYXJlbnQgMSAwIFIKL1Jlc291cmNlcyAyIDAgUgovTWVkaWFCb3ggWzAgMCAxMjgwLiA1NDAuXQovQ29udGVudHMgNCAwIFIKPj4KZW5kb2JqCjQgMCBvYmoKPDwvTGVuZ3RoIDU4MDMxPj4Kc3RyZWFtCjAuMjAwMDI1IHcKMCBHCnEKMS4gMC4gMC4gLTEuIDAuIDU0MC4gY20KL0YxIDE2IFRmCnEKMS4gMC4gMC4gMS4gMC4gMC4gY20KMS4wMCB3CjAuMDAgZwovRjkgMTYgVGYKL0Y5IDE2IFRmCnEKL0YxNSAxNiBUZgovRjE1IDEyIFRmCnEKUQpxCi9HUzEgZ3MKNS4wMCB3CjAuMDAgRwoxLiAwLiAwLiAxLiAxLiAxLiBjbQo0LiA0LiBtCjEy...AwMjAgMDAwMDAgbiAKMDAwMDA5MjQxNyAwMDAwMCBuIAowMDAwMDkzMzA1IDAwMDAwIG4gCjAwMDAwOTM1MDQgMDAwMDAgbiAKMDAwMDA5NDA5NCAwMDAwMCBuIAowMDAwMDk0MjM4IDAwMDAwIG4gCjAwMDAwOTQyNjkgMDAwMDAgbiAKMDAwMDA5NDMwMCAwMDAwMCBuIAowMDAwMDk0MzMxIDAwMDAwIG4gCjAwMDAwOTQ2NjIgMDAwMDAgbiAKMDAwMDA5NTEzNiAwMDAwMCBuIAowMDAwMDk1MjIyIDAwMDAwIG4gCnRyYWlsZXIKPDwKL1NpemUgMzEKL1Jvb3QgMzAgMCBSCi9JbmZvIDI5IDAgUgovSUQgWyA8M0VDRDZEMUJBNDcyREY2QUFGNjcyRUQ0MzA2NkE1REE+IDwzRUNENkQxQkE0NzJERjZBQUY2NzJFRDQzMDY2QTVEQT4gXQo+PgpzdGFydHhyZWYKOTUzMjYKJSVFT0Y='.
```

This error is only happening on iOS (latest) Safari (latest).

One solution is to add an iframe block to the dataURL while calling doc.write() --> [Solution link](https://ourcodeworld.com/articles/read/682/what-does-the-not-allowed-to-navigate-top-frame-to-data-url-javascript-exception-means-in-google-chrome)

Can you help me in finding the correct file in Highcharts library where I need to make this change?

**Comment by KacperMadej** [comment]
We are using https://code.highcharts.com/9.0.1/lib/svg2pdf.js for PDF generation but I am unable to find any `write` call in both `offline-exporting` module and `svg2pdf`. Your link gives a solution for Chrome while you get the error in Safari - shouldn't you be able to recreate the problem in Chrome?

There might be an issue with the sandbox itself - please try with a stand-alone HTML document.

**Comment by roychowdhuryrohit-dev** [comment]
> We are using https://code.highcharts.com/9.0.1/lib/svg2pdf.js for PDF generation but I am unable to find any `write` call in both `offline-exporting` module and `svg2pdf`. Your link gives a solution for Chrome while you get the error in Safari - shouldn't you be able to recreate the problem in Chrome?
> 
> There might be an issue with the sandbox itself - please try with a stand-alone HTML document.

1. There's no way I can access the Chrome's console on iOS (latest) platform. I can only access Safari's console by connecting it to a macOS device.
2. My original iOS error is only happening when I'm testing it with a stand-alone HTML document which is why I am not able to recreate it inside the sandbox.

**Comment by KacperMadej** [comment]
I now see why I was confused. The initial issue was reported with error logs from Chrome and later the issue changed to something else - errors on iOS.

Please add the HTML file that should be used for testing and information about your iOS version.

**Comment by KacperMadej** [comment]
Closing due to inactivity
