### ISSUE TITLE
[Bug] Highcharts v10, Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by totszwai** [highcharts/highcharts#17300]
#### Expected behaviour
To not throw error when no ticks are defined.

#### Actual behaviour

<img width="613" alt="image" src="https://user-images.githubusercontent.com/4440365/168656738-f57ff6b5-04de-4d13-a82a-762d4c34758b.png">

The bug is here
https://github.com/highcharts/highcharts/blob/0146821d369ddc8af5db75afb8fb5257185673c9/ts/Core/Axis/Axis.ts#L2057

You try to access `tickPositions` when `tickPositions` itself is undefined at:
https://github.com/highcharts/highcharts/blob/0146821d369ddc8af5db75afb8fb5257185673c9/ts/Core/Axis/Axis.ts#L1995

#### Product version
v10.

**Comment by raf18seb** [comment]
Hi @totszwai, thank you for contacting us with your issue.

Could you provide a live simplified jsFiddle demo showing the issue, please? Thank you in advance!

**Comment by giovdk21** [comment]
hi, I just came across the same issue:

```
at unstable_runWithPriority ([...]/node_modules/scheduler/cjs/scheduler.development.js:653:12) TypeError: Cannot read properties of undefined (reading 'length')
at a27.tickPositions [as setTickPositions] ([...]/node_modules/highcharts/highstock.js:205:165)
at a27.setTickInterval ([...]/node_modules/highcharts/highstock.js:202:476)
at a27.setScale ([...]/node_modules/highcharts/highstock.js:212:120)
at [...]/node_modules/highcharts/highstock.js:396:196
```

(I'm using highstock)

A few things I noticed so far:
- happens when running tests (react 16.14 + jest 26 + enzyme 3.11), but loads fine on the browser
- it works with version `10.0.0`, breaks with `10.1.0`
- doesn't break if `series.data` is empty or an array of just 1 element

**Comment by mdcrawford** [comment]
I think this is related (let me know if it's separate) – I'm seeing something similar in a case where I'm calling `axis.getExtremes()` inside of `chart.events.load` which causes a crash.  Only seeing on v10.1.0, not on v.10.0.0.

Stack trace:
![Screen Shot 2022-05-19 at 2 50 37 PM](https://user-images.githubusercontent.com/17690819/169377979-b4fe8d01-9c88-4bfd-9ca0-b185ae8d7561.png)

**Comment by pawellysy** [comment]
Hello @mdcrawford, could you share the demo, where the issue is reproduced? This will allow me to determine, what is the reason for the problem to occur

**Comment by chyzwar** [comment]
We have same issue.

**Comment by pawellysy** [comment]
@mdcrawford  @chyzwar Sorry guys, without the demo or any reproduction steps we are unable to investigate the issue. In order to allow us to do some work, please share the demo. Thanks!

**Comment by chyzwar** [comment]
@pawellysy did you tried @temka1234 repro?

**Comment by temka1234** [comment]
Create repo with `npx create-react-app highcharts-test --template typescript`
https://github.com/temka1234/highcharts-set-data-bug-17300

File:
`src/highcharts.test.ts`

Steps:
`npm install`
`npm run test`

![Screenshot 2022-05-27 124427](https://user-images.githubusercontent.com/3648995/170675093-bf161b36-ffe2-4a27-bb45-6f14c9da313a.png)

**Comment by chyzwar** [comment]
@pawellysy can you check repro provided by temka

**Comment by pawellysy** [comment]
Hi, @chyzwar I managed to reproduce the problem, thanks a lot for the specific reproduction steps!

The problem was probably connected to the fact, that Jest created the div, but didn't apply inline styles to the div. So that the chart's container size had some small values. This leads to having some values equal to `NaN` because of the division by 0.

As a workaround, you can set the xAxis' width like this
```js
xAxis: {
    width: '100%'
}
```

Let me know if that fixes this problem. We will search for some permanent solution soon. Thanks!

**Comment by Techn1x** [comment]
I hit this issue today. Unfortunately, both the width: 100% and tickAmount: 100 workarounds did not work for me.

Pinning to v10.0.0 is the workaround for me for now.

**Comment by pawellysy** [comment]
Hello @Techn1x, could you share your Jest configuration, so that I could investigate your issue?
Also, what do you mean, by saying that `Pinning to v10.0.0 is the workaround for me for now.`?
Is everything working in order in the v10.0.0? Thanks!

**Comment by mdcrawford** [comment]
I can confirm the bug goes away for me in 10.0.0

**Comment by chyzwar** [comment]
Workaround suggested do not work in 10.2.1. Only pinning to 10.0.0 resolve issue.

**Comment by TorsteinHonsi** [comment]
@chyzwar @pawellysy I suspect this latest regression is a duplicate of #17678.

**Comment by totszwai** [comment]
It is the best practices to check for the object before checking for its `.length`. Regardless of where the upstream cause of this error... 
```
if (tickPositions && tickPositions.length && /* ...whatever */) { 
```

Regardless, it looks like the entire logic block from [line 1995](https://github.com/highcharts/highcharts/blob/0146821d369ddc8af5db75afb8fb5257185673c9/ts/Core/Axis/Axis.ts#L1995) never did its job to properly initialize the tickPositions. That final `else` case still didn't compute `tickPositions`.

I don't know the old Highcharts logic history of the code, but
- IF, the L1995 block failed to compute the `tickPositions` and is deemed OK, then you should just add my proposed check by checking for `tickPositions && tickPositions.length` and close this.
- IF, the L1995 block's `else` supposed to **always** compute a `tickPositions`, then perhaps fix that `else` block.


I don't think the "workaround" is actually a legit workaround, if the user disables all the axis, wouldn't make sense to have any axis set it "100%".

**Comment by Techn1x** [comment]
> Hello @Techn1x, could you share your Jest configuration, so that I could investigate your issue?

Sorry for the delay in my response - this occurs for me in any build, not just tests.... and for what it's worth I use qunit not jest

**Comment by pawellysy** [comment]
@TorsteinHonsi, checked on master and still throws an error.

**Comment by pawellysy** [comment]
@Techn1x, could you share your configuration, where the issue is reproduced outside of your test suite?

**Comment by Techn1x** [comment]
@pawellysy 

In the process of getting my config together I realised what is causing the issue, at least for me.
I had `yAxis.min: Infinity` and `yAxis.max: -Infinity`........ which is the wrong way around.

I am guessing that before, these invalid values were ignored or something. But when I put them the correct way around, it now works great. Alternatively, `yAxis.min: undefined` and `yAxis.max: undefined` is also valid

**Comment by pawellysy** [comment]
@Techn1x, So in your example, this was not a bug, just a config error. So this bug is still a problem in the test environment in react.

**Comment by pawellysy** [comment]
@totszwai, I've investigated the issue with the Highcharts version from the master branch, and the bug seems to be resolved.
You can check this yourself, by copying the code from `https://github.highcharts.com/highcharts.js`, putting it in the src directory of your repository, and importing it `import Highcharts from "./Highcharts";` instead of `import Highcharts from "highcharts";` let me know if that works for you! If so, we will close this issue as a duplicate of an issue mentioned earlier.

**Comment by pawellysy** [comment]
We are making releases every 1.5 - 2 months, and the last one was 29.09.2022r, so the next release will be in about a month. For now, please use the proposed workaround I mentioned above.

**Comment by MightyPork** [comment]
I have a similar issue that's reproduced by this (I kept deleting things from the JSON until only this was left).

the "xAxis" workaround isn't working in this case (`xAxis: {width: '100%'}`)

```
Highcharts.chart('container', {
    "series": [
        {
            "data": [],
            "threshold": 0,
        }
    ],
    "yAxis": [
        {
            "ceiling": 1,
        }
    ]
});
```

It goes away if the series has some data added, or threshold:0 or ceiling:1 is removed.

```
highcharts.js:204 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at a.setTickPositions (highcharts.js:204:50)
    at a.setTickInterval (highcharts.js:201:328)
    at a.setScale (highcharts.js:210:481)
    at highcharts.js:395:252
    at Array.forEach (<anonymous>)
    at a.render (highcharts.js:395:230)
    at a.firstRender (highcharts.js:399:194)
    at a.<anonymous> (highcharts.js:368:178)
    at E (highcharts.js:18:319)
    at a.init (highcharts.js:366:208)
```

Is that the same issue? What workaround can be used other than waiting for the next release? Pin to `10.0.0`? We are using `10.2.0`

**Comment by pawellysy** [comment]
Hi @MightyPork, this is the same issue, which is also fixed on the master branch. The above workaround applies :)
