### ISSUE TITLE
Tooltip giving out exception error in V10.2 of highcharts-more.js

### ISSUE THREAD

**Issue by James-76** [highcharts/highcharts#17480]
#### Expected behaviour

![image](https://user-images.githubusercontent.com/59254774/177849337-282367e4-725d-4a46-8570-d9db26dff5be.png)

#### Actual behaviour

![image](https://user-images.githubusercontent.com/59254774/177848602-e4b32631-5fa1-415b-aa1f-845a23bf666d.png)

#### Product version
        <script type='text/javascript' src='//code.highcharts.com/stock/highstock.js'></script>
        <script type='text/javascript' src='//code.highcharts.com/10.2/highcharts-more.js'></script>
        <script type='text/javascript' src='//code.highcharts.com/modules/exporting.js'></script>
        <script type='text/javascript' src='//code.highcharts.com/modules/solid-gauge.js'></script>

#### Affected browser(s)
Firefox, Edge

Error message
highcharts-more.src.js:12075 
 Uncaught TypeError: Cannot read properties of undefined (reading 'chart')
    at b.searchPointByAngle [as searchPoint] (highcharts-more.src.js:12075:29)
    at highstock.src.js:27211:33
    at Array.forEach (<anonymous>)
    at d.findNearestKDPoint (highstock.src.js:27207:17)
    at d.getHoverData (highstock.src.js:27377:25)
    at d.runPointActions (highstock.src.js:28056:33)
    at d.onContainerMouseMove (highstock.src.js:27685:25)

I can see looking in the src file that the code has been modified in this area

line 12073:
            PolarAdditions.prototype.searchPointByAngle = function (e) {
                var series = this.series,
                    chart = series.chart,

rather than line 11208:
        seriesProto.searchPointByAngle = function (e) {
            var series = this,
                chart = series.chart,

**Comment by James-76** [comment]
Closing as a duplicate of #17472
