### ISSUE TITLE
Not able to render a pie chart 3d due to w.pushUnique is not a function

### ISSUE THREAD

**Issue by andrewtabata** [highcharts/highcharts#18893]
#### Expected behaviour
Render a pie chart 3d in the browser.

#### Actual behaviour

Affected sources: 
highcharts-3d.src.js
exporting.src.js

Error: Cannot read properties of undefined (reading '0') due to 
Uncaught TypeError: w.pushUnique is not a function
    at g.compose (highcharts-3d.src.js:3019:21)
    at highcharts-3d.src.js:5006:9
    at C (highcharts-3d.src.js:26:25)
    at highcharts-3d.src.js:5000:5
    at highcharts-3d.src.js:19:9
    at highcharts-3d.src.js:8:2

 and 
Uncaught TypeError: l.pushUnique is not a function
    at B.compose (exporting.src.js:1134:21)
    at e.compose (exporting.src.js:1913:17)
    at exporting.src.js:2866:9
    at e (exporting.src.js:28:25)
    at exporting.src.js:2859:5
    at exporting.src.js:21:9
    at exporting.src.js:10:2
TypeError: Cannot read properties of undefined (reading '0')
    at G.translate3dPoints (highcharts-3d.src.js:3835:117)
    at G.<anonymous> (highcharts-3d.src.js:3890:17)
    at highcharts.src.js:1663:26
    at Array.forEach (<anonymous>)
    at y (highcharts.src.js:1662:28)
    at g.translate (highcharts.src.js:8:2)
    at G.translate (highcharts-3d.src.js:4670:17)
    at a.E (highcharts-3d.src.js:2896:25)
    at b.<computed> [as renderSeries] (highcharts.src.js:840:41)
 

#### Live demo with steps to reproduce

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/3d-pie
#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
This occurs because the old version of highcharts.js is cached, while highcharts-3d.js loads the new version. The issue does not occur in our offices (Norway and Poland), but I suspect it may have to do with regional CloudFlare cache. Will investigate.

**Comment by TorsteinHonsi** [comment]
@andrewtabata I purged the CloudFlare cache again, can you try a hard refresh now?

**Comment by semichrist** [comment]
appears to be working for now, though the issue was intermittent to begin with. highcharts.com is still showing a cloudflare screen before loading, which makes me suspicious.
