### ISSUE TITLE
Maximum call size exceeded bar race chart

### ISSUE THREAD

**Issue by felhag** [highcharts/highcharts#18950]
I was playing around with the [bar race chart](https://www.highcharts.com/demo/bar-race) which looks really neat! It works great but it throws an error when resizing your browser window. A workaround could be setting a hardcoded container width, but of course this prevents rescaling your container at all. 

#### Expected behaviour
Resizing with a running bar race chart should not throw errors.

#### Actual behaviour
It ends up in an endless loop: 

```
highcharts.src.js:9266 Uncaught RangeError: Maximum call stack size exceeded
    at u.attr (highcharts.src.js:9266:17)
    at label.attr (?editor_console=true:226:41)
    at label.attr (?editor_console=true:223:38)
    at u.animate (highcharts.src.js:9116:21)
    at label.attr (?editor_console=true:224:38)
    at u.animate (highcharts.src.js:9116:21)
    at label.attr (?editor_console=true:224:38)
    at u.animate (highcharts.src.js:9116:21)
    at label.attr (?editor_console=true:224:38)
    at u.animate (highcharts.src.js:9116:21)
```

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/bar-race
- open javascript console
- press play
- resize container (by resizing browser or resizing in jsfiddle)

#### Product version
Highcharts 11.0.0

#### Affected browser(s)
Chrome

**Comment by karolkolodziej** [comment]
Hi @felhag!
I'm happy to hear that you like this chart!

Regarding your issue, you must ensure the labels are not updated during the resize.
Please use the `isResizing` flag on the chart as in [the demo.](https://jsfiddle.net/BlackLabel/pydwe12h/)
