### ISSUE TITLE
Bar charts have suddenly stopped rendering

### ISSUE THREAD

**Issue by sjw31463** [highcharts/highcharts#19007]
#### Expected behaviour

Hello all,
I used Highcharts 'Bar' series on a project a few weeks ago. Everything was working fine for weeks on end, but I came back around to do some touch-up work on it, and suddenly none of my charts are rendering. Below is an image of what the chart basically looked like before: 
![image](https://github.com/highcharts/highcharts/assets/49414965/d56733c7-4c71-4919-b42d-590cf0ce8e26)

#### Actual behaviour

No part of the chart is rendering, and I get this console error for each one: 
**Uncaught TypeError: Cannot create property 'userOptions' on boolean 'false'
    at aa.<anonymous> (highstock.src.js:28761:21)
    at e (highstock.src.js:1644:17)
    at aa.init (highstock.src.js:28748:17)
    at aa.getArgs (highstock.src.js:28724:21)
    at new aa (highstock.src.js:28697:17)
    at Object.success (givingday:5156:15)
    at b.onreadystatechange (data.src.js:122:52)**

#### Live demo with steps to reproduce
https://jsfiddle.net/sydney_wakeford/L6dyqxo5/9/

Here is one of my bar charts that I tried to isolate to narrow down the problem with. On JSFiddle, I am only getting "Script error." with no other information. Unsure at this point if the problem is coming from something that has changed on our end or Highcharts'. 
Any information is helpful! 

#### Product version
I'm loading from the CDN, i.e. v11.0.1.

#### Affected browser(s)
Chrome; Firefox

**Comment by sjw31463** [comment]
Update: Forgot to check closed issues, and I found the problem and solution on ticket [#16201 ](url). Closing!
