### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'replace')

### ISSUE THREAD

**Issue by tzurik** [highcharts/highcharts#19105]
Expected behaviour
Show tooltip on datetime graph

Actual behaviour
No tooltip is shown and errors are thrown to the console

Live demo with steps to reproduce
Sorry, it's a bit hard for me for it's a very complicated structure

Product version
highcharts: 10.3.3

Affected browser(s)
Tested in just Chrome

Hi
I created a datetime chart and when hovering on the column I get this error instead of the tooltip:
highcharts.js:275 Uncaught TypeError: Cannot read properties of null (reading 'replace')
    at eval (highcharts.js:275:338)
    at Array.forEach (<anonymous>)
    at a.eval (highcharts.js:275:268)
    at y (highcharts.js:18:293)
    at a.tooltipFooterHeaderFormatter (highcharts.js:275:161)
    at a.defaultFormatter (highcharts.js:255:217)
    at a.refresh (highcharts.js:266:75)
    at g.eval (highcharts.js:323:153)
    at y (highcharts.js:18:293)
    at g.firePointEvent (highcharts.js:282:387)

I tried to debug it but it does not even enter the tooltip formatter (which is configured from the series object).
In linear/category charts everything is working great. More than that, to this exact graph, when I sent izo instead of a timestamp, the tooltip worked (of course the whole graph behaved like a category graph so I had to change it)

Is there a quick fix for it (for because I have a code freeze tomorrow... )?

**Comment by bm64** [comment]
Hello @tzurik and thanks for contacting us.

The code that you provided seems to be minified and thus it won't help me with finding which part exactly is failing. Nevertheless, based on your description it sounds that there might be many possible causes of that issue and to tell what exactly is wrong I will need you to provide me with reproduction of that issue. You can start here: https://jsfiddle.net/BlackLabel/62Lz3ugt/

**Comment by tzurik** [comment]
Hi
I managed to isolate the cause to the exception: In the configuration of the tooltip, headerFormat was set to null. Changing it to an rmpty string solved the problem.
The thing is, in other datatypes (linear and category) "null" passed just fine, it broke only on datetime, so you ma want to check it...

**Comment by bm64** [comment]
@tzurik as you can see in the [Highcharts API documentation](https://api.highcharts.com/highcharts/tooltip.headerFormat), the headerFormat should be either a `string` type or `undefined`. Unfortunately, your description still doesn't provide enough information for me to understand the exact outcome you're trying to achieve. However, using null as a value for headerFormat is currently considered a misconfiguration of the chart and is not classified as a bug. 

We use github strictly as a bug / feature tracking tool, so in case of any further questions regarding this matter, please visit out other support channels where our team will help you with finding the solution: https://www.highcharts.com/blog/support/
