### ISSUE TITLE
TypeError: e.getAttribute is not a function

### ISSUE THREAD

**Issue by aa-ihorskliar** [highcharts/highcharts#19628]
#### Details
Our Sentry time to time catches this exception.
Unfortunately, I have no idea how to reproduce this issue because stack trace is too minimal.

```
TypeError: e.getAttribute is not a function
  at n(./node_modules/highcharts/highcharts.js:14:106)
  at d(./node_modules/highcharts/highcharts.js:14:193)
  at a.prototype.inClass(./node_modules/highcharts/highcharts.js:310:317)
  at a.prototype.onDocumentMouseMove(./node_modules/highcharts/highcharts.js:315:373)
  at this.unDocMouseMove(./node_modules/highcharts/highcharts.js:323:454)
  at sentryWrapped(./node_modules/@sentry/browser/esm/helpers.js:73:23)
```

It happens when user click some element `.highcharts-container. > svg`.

#### Product version
```json
"highcharts": "10.3.3",
"highcharts-react-official": "3.0.0",
"highcharts-regression": "2.2.0",
```

#### Affected browser(s)
It was caught on `Windows >= 10`, `Mac OS X >=10.15.7`, ` Chrome 116.0.0`, and ` Chrome 115.0.0`.

**Comment by karolkolodziej** [comment]
Hi @aa-ihorskliar! 

Is there any chance to share more details about what the series is and what are the steps to recreate it?
Without that, it might be difficult to trace the source since the `getAttribute` is a widely used function.

**Comment by aa-ihorskliar** [comment]
Hi @karolkolodziej, unfortunately or Sentry didn't captured anything more. I'll definitely post here an additional information if I get one in the future.

**Comment by KacperMadej** [comment]
Closing due to inactivity. If it is possible to recreate the problem this issue could be reopened or you can open a new one.
