### ISSUE TITLE
Gantt charts exception in 11.1 vs 10.3.3

### ISSUE THREAD

**Issue by castortech** [highcharts/highcharts#19704]
#### Expected behaviour
No exception

#### Actual behaviour
Exception reported
Uncaught TypeError: Cannot read properties of undefined (reading 'isActive')
    at highcharts-gantt.src.js:42112:33
    at Array.forEach (<anonymous>)
    at x.d [as drawDataLabels] (highcharts-gantt.src.js:41947:21)
    at x.render (highcharts-gantt.src.js:33503:21)
    at highcharts-gantt.src.js:36597:21
    at Array.forEach (<anonymous>)
    at B.renderSeries (highcharts-gantt.src.js:36595:17)
    at B.render (highcharts-gantt.src.js:36678:17)
    at B.firstRender (highcharts-gantt.src.js:36837:17)
    at B.<anonymous> (highcharts-gantt.src.js:35276:21)

Debugging shows that the datalabels array as a length of 3, with nothing at index 0.

This seems to correlate with the data that contains a first element that is empty:
 `    "dataLabels": [
      {}, 
      {
      "enabled": true,
      ...
`

#### Live demo with steps to reproduce
Run: https://jsfiddle.net/alpic80/wgdL5r3n/14/

switch script to 10.3.3 by uncommenting in header and error will go away.

#### Product version
Highcharts Gantt 11.1 (works in 10.3.3)

#### Affected browser(s)
All

**Comment by bm64** [comment]
Hello @castortech and thanks for reporting the issue.

_Internal note:_
Bisected to: 7d466d61894c6382ff995735e57a46a74f8a4e9e

**Comment by goransle** [comment]
The issue described here was fixed in version 11.2. Some additional errors caused by `yAxis.scrollbar` were solved in #20131, and will be part of the next release.
