### ISSUE TITLE
Test "Highcharts Soft series and axis update by data module update, datetime axis" fails

### ISSUE THREAD

**Issue by srafay** [highcharts/highcharts#20021]
#### Expected behaviour
All tests should pass or should be skipped if are not valid anymore.

#### Actual behaviour
Chrome Headless (Windows 10) Highcharts Soft series and axis update by data module update, datetime axis FAILED
        Initial time should be set - actual time varies with timezone
        Expected: true
        Actual: false
        Debug: http://utils.highcharts.local/samples/#test/unit-tests/chart/chart-update-data
            at Object.<anonymous> (samples/unit-tests/chart/chart-update-data/demo.js:63:16)
            at runTest (node_modules/qunit/qunit/qunit.js:2725:35)
            at Test.run (node_modules/qunit/qunit/qunit.js:2708:9)
            at node_modules/qunit/qunit/qunit.js:2979:16
            at processTaskQueue (node_modules/qunit/qunit/qunit.js:2293:26)
            at node_modules/qunit/qunit/qunit.js:2297:13

#### Live demo with steps to reproduce
N/A

#### Product version
11.1.0

#### Affected browser(s)
N/A

**Comment by karolkolodziej** [comment]
Hi @srafay!

Could you please elaborate on where and how it fails?
I've tried with the latest master and everything passes.
```bash
>npx gulp test --tests unit-tests/chart/chart-update-data
[08:47:14] Using gulpfile ~/repos/highcharts/gulpfile.js
[08:47:14] Starting 'test'...
[08:47:14] Starting 'test-docs'...
[08:47:14] Checking links to samples in *.ts files...
[08:47:15] Checking links to samples in *.md files...
[08:47:15] Finished 'test-docs' after 304 ms
[08:47:15] Starting 'scripts'...
[08:47:16] ✓ Source code has not been modified since the last successful run.
[08:47:16] Hint: Run the `scripts-watch` task to watch the js and ts directories.
[08:47:16] Finished 'scripts' after 1.02 s
[08:47:16] Starting 'test'...
[08:47:17] Run `gulp test --help` for available options
30 10 2023 08:47:17.529:WARN [karma-server]: Passing raw CLI options to `new Server(config, done)` is deprecated. Use `parseConfig(configFilePath, cliOptions, {promiseConfig: true, throwErrors: true})` to prepare a processed `Config` instance and pass that as the `config` argument instead.
(node:78876) Warning: Accessing non-existent property 'VERSION' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
30 10 2023 08:47:17.767:INFO [framework:karma-sharding]: sharding specs across 6 browsers
30 10 2023 08:47:22.651:INFO [karma-server]: Karma v6.4.2 server started at http://localhost:9876/
30 10 2023 08:47:22.653:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
30 10 2023 08:47:22.661:INFO [launcher]: Starting browser ChromeHeadless
30 10 2023 08:47:23.888:INFO [Chrome Headless 118.0.5993.117 (Mac OS 10.15.7)]: Connected on socket U7rkIZZyQk4Ukxd_AAAB with id 96113047
Chrome Headless 118.0.5993.117 (Mac OS 10.15.7) SLOW 3.114 secs: Highcharts Soft series update by data module update
Chrome Headless 118.0.5993.117 (Mac OS 10.15.7) SLOW 3.274 secs: Highcharts Soft series and axis update by data module update, datetime axis
Chrome Headless 118.0.5993.117 (Mac OS 10.15.7): Executed 2 of 2 SUCCESS (6.479 secs / 6.388 secs)
TOTAL: 2 SUCCESS
[08:47:33] Finished 'test' after 18 s
[08:47:33] Finished 'test' after 19 s
```

**Comment by srafay** [comment]
@karolkolodziej not sure why its failing for me...

```
srafay@PC MINGW64 /d/Projects/highcharts (master)
$ node -v
v20.9.0

srafay@PC MINGW64 /d/Projects/highcharts (master)
$ npm -v
10.2.1

srafay@PC MINGW64 /d/Projects/highcharts (master)
$ git pull
Already up to date.

srafay@PC MINGW64 /d/Projects/highcharts (master)
$ npx gulp test --tests unit-tests/chart/chart-update-data
[21:27:59] Using gulpfile D:\Projects\highcharts\gulpfile.js
[21:27:59] Starting 'test'...
[21:27:59] Starting 'test-docs'...
[21:27:59] Checking links to samples in *.ts files...
[21:27:59] Checking links to samples in *.md files...
[21:27:59] Finished 'test-docs' after 309 ms
[21:27:59] Starting 'scripts'...
[21:28:00] ✓ Source code has not been modified since the last successful run.
[21:28:00] Hint: Run the `scripts-watch` task to watch the js and ts directories.
[21:28:00] Finished 'scripts' after 585 ms
[21:28:00] Starting 'test'...
[21:28:00] Run `gulp test --help` for available options
30 10 2023 21:28:00.227:WARN [karma-server]: Passing raw CLI options to `new Server(config, done)` is deprecated. Use `parseConfig(configFilePath, cliOptions, {promiseConfig: true, throwErrors: true})` to prepare a processed `Config` instance and pass that as the `config` argument instead.
(node:35992) Warning: Accessing non-existent property 'VERSION' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
30 10 2023 21:28:00.429:INFO [framework:karma-sharding]: sharding specs across 10 browsers
30 10 2023 21:28:09.669:INFO [karma-server]: Karma v6.4.2 server started at http://localhost:9876/
30 10 2023 21:28:09.669:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
30 10 2023 21:28:09.681:INFO [launcher]: Starting browser ChromeHeadless
30 10 2023 21:28:10.373:INFO [Chrome Headless 118.0.5993.118 (Windows 10)]: Connected on socket tRcZ1YAh98r-vi0eAAAB with id 59866806
Chrome Headless 118.0.5993.118 (Windows 10) Highcharts Soft series and axis update by data module update, datetime axis FAILED
        Initial time should be set - actual time varies with timezone
        Expected: true
        Actual: false
        Debug: http://utils.highcharts.local/samples/#test/unit-tests/chart/chart-update-data
            at Object.<anonymous> (samples/unit-tests/chart/chart-update-data/demo.js:63:16)
            at runTest (node_modules/qunit/qunit/qunit.js:2697:35)
            at Test.run (node_modules/qunit/qunit/qunit.js:2680:9)
            at node_modules/qunit/qunit/qunit.js:2951:16
            at processTaskQueue (node_modules/qunit/qunit/qunit.js:2271:26)
            at node_modules/qunit/qunit/qunit.js:2275:13
Chrome Headless 118.0.5993.118 (Windows 10): Executed 2 of 2 (1 FAILED) (0.002 secs / 0.119 secs)
TOTAL: 1 FAILED, 1 SUCCESS
[21:28:10] 'test' errored after 11 s
[21:28:10] Error in plugin "karma"
Message:
    Tests failed
[21:28:10] 'test' errored after 12 s

```

**Comment by karolkolodziej** [comment]
I've tested this test also on the windows and there is no difference- still everything passes.

But there might be one thing which causes all of it- time change.
Recently, in central Europe, we changed to the DST. I'm not sure where you are from, but it might have something to do with it. And since there are some time-related calculations in this test, this will be my main suspect. 

You can try to fiddle a bit with the timezone and see if it changes anything.
