### ISSUE TITLE
Highcharts breaking build when using Next 14.0.2 in NX

### ISSUE THREAD

**Issue by gcko** [highcharts/highcharts#20129]
#### Expected behaviour
Production build will successfully generate for Next version `14.0.2`

#### Actual behaviour
Production build fails with ```TypeError: Cannot read properties of undefined (reading 'document')```

#### Live demo with steps to reproduce
[![Edit gcko/reproduction/main](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/github/gcko/reproduction/main?import=true&embed=1&file=%2F.codesandbox%2Ftasks.json&showConsole=true)

#### Product versions
```json
{
  "nx": "17.1.2",
  "highcharts": "11.2.0",
  "next": "14.0.2"
}
```

#### Affected browser(s)
N/A

**Comment by gcko** [comment]
I am also tracking this here as well: https://github.com/nrwl/nx/issues/20231

**Comment by etrinh** [comment]
looks similar to: https://github.com/vercel/next.js/issues/58379

**Comment by gcko** [comment]
@etrinh Yes, it looks similar. The reproducer I created narrows it down to the `highcharts` package - I removed `highcharts-react-official` as part of debugging

**Comment by gcko** [comment]
@etrinh here is a link to the reproducer: https://github.com/gcko/reproduction

**Comment by karolkolodziej** [comment]
Hi @gcko!

Thank you for sharing that! It looks like if you import Highcharts as an es-module everything complies correctly.
```ts
import Highcharts from 'highcharts/es-modules/masters/highcharts.src';
```

Looks like the Next doesn't compile CommonJS modules? Any insights about that?

**Comment by gcko** [comment]
@karolkolodziej by default Next uses the following `tsconfig.json`: 

```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
```

Because this points to `"module": "esnext"` and not `"module": "commonjs"`, that might be a part of the issue. One thing to  note, this has been the standard for around 3 years, so this might be a red herring.

**Comment by karolkolodziej** [comment]
@gcko I'm fiddling around with the `tsconfig` but I'm not able to make it work with CommonJS- I get this error all the time.
So you might be right and it is a dead end.

**Comment by karolkolodziej** [comment]
Altho it must be strictly related to how Highcharts are imported/exported because I get the same error even with component like this.
```tsx
'use client';
import * as Highcharts from 'highcharts';

export default function Index() {
  console.log(Highcharts);

  return <div id="container" />;
}
```

**Comment by gcko** [comment]
hmmm. @karolkolodziej I switched to try using es-module imports and am now receiving a different error

Imports being used:
```typescript
import Highcharts from 'highcharts/es-modules/masters/highcharts.src';
import 'highcharts/es-modules/masters/modules/exporting.src';
import 'highcharts/es-modules/masters/modules/accessibility.src';
```

Error:
```bash
TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at addEvent (/Users/jaredmscott/repos/tkspring/ts-pro-frontend/dist/apps/ts-pro/.next/server/chunks/185.js:6:3378)
    at t.compose (/Users/jaredmscott/repos/tkspring/ts-pro-frontend/dist/apps/ts-pro/.next/server/chunks/185.js:21:35409)
    at t.compose (/Users/jaredmscott/repos/tkspring/ts-pro-frontend/dist/apps/ts-pro/.next/server/chunks/185.js:21:139162)
    at 88073 (/Users/jaredmscott/repos/tkspring/ts-pro-frontend/dist/apps/ts-pro/.next/server/chunks/185.js:21:152920)
    at t (/Users/jaredmscott/repos/tkspring/ts-pro-frontend/dist/apps/ts-pro/.next/server/webpack-runtime.js:1:142)
    at 21813 (/Users/jaredmscott/repos/tkspring/ts-pro-frontend/dist/apps/ts-pro/.next/server/chunks/495.js:1:4739)
    at t (/Users/jaredmscott/repos/tkspring/ts-pro-frontend/dist/apps/ts-pro/.next/server/webpack-runtime.js:1:142)
    at 82766 (/Users/jaredmscott/repos/tkspring/ts-pro-frontend/dist/apps/ts-pro/.next/server/app/(authenticated)/market/page.js:1:2821)
    at t (/Users/jaredmscott/repos/tkspring/ts-pro-frontend/dist/apps/ts-pro/.next/server/webpack-runtime.js:1:142)
```

I traced down the error, and it is coming from Line 1389 in `node_modules/highcharts/es-modules/Core/Utilities.js`:
```javascript
// function addEvent()....
// ... more code
if (!Object.hasOwnProperty.call(owner, 'hcEvents')) {
        owner.hcEvents = {};
    }
// ...
```

**Comment by karolkolodziej** [comment]
Did you have any of the issues above with the earlier version of Next.js? Or is it lately after the update to v14?
If so, any idea what might have caused this issue? I'm not super familiar with Next.js so if you can give me a hint that would be great.

**Comment by gcko** [comment]
@karolkolodziej the issue did not begin until updating from `14.0.1` to `14.0.2`. Versions `14.0.1` and prior all work fine using `import * as Highcharts from 'highcharts';`

This might be an issue with the work Vercel (the creators of NextJS) are doing with their compiler. They have their own, TurboPack, that they are building, but right now IIRC they are using SWC. It seems to be related to changes that occurred between 14.0.1 and 14.0.2

**Comment by etrinh** [comment]
In highcharts.src.js: 
```
/**
 * @license Highcharts JS v11.2.0 (2023-10-30)
 *
 * (c) 2009-2021 Torstein Honsi
 *
 * License: www.highcharts.com/license
 */
(function (root, factory) {
    if (typeof module === 'object' && module.exports) {
        factory['default'] = factory;
        module.exports = root.document ?
            factory(root) :
            factory;
    } else if (typeof define === 'function' && define.amd) {
        define('highcharts/highcharts', function () {
            return factory(root);
        });
    } else {
        if (root.Highcharts) {
            root.Highcharts.error(16, true);
        }
        root.Highcharts = factory(root);
    }
}(typeof window !== 'undefined' ? window : this, function (window) {
```

`}(typeof window !== 'undefined' ? window : this, function (window) {`
Is built by nextjs to:
`}( false ? 0 : void 0, function(t) {`
Which makes `root.document` on line 11 crash.
During next's build, both document and window are undefined.

Maybe it is stupid, but what about replacing `root.document` by `root?.document` on line 11?

**Comment by gcko** [comment]
@karolkolodziej I got it to build successfully using ES Modules, however I had to remove my imports for the accessibility module: `import 'highcharts/es-modules/masters/modules/accessibility.src';`

I traced the failing code [above](https://github.com/highcharts/highcharts/issues/20129#issuecomment-1813990090) more thoroughly and found that it is coming from the Accessibility module. 

specifically, here is what I found:

`node_modules/highcharts/es-modules/Accessibility/KeyboardNavigation.js` Line 417
```javascript
if (U.pushUnique(composedMembers, doc)) {
            addEvent(doc, 'keydown', documentOnKeydown);
        }
```
`doc` is being passed to `addEvent` as `null` or  `undefined`

`doc` is coming from the following on Line 13 & 14
```javascript
import H from '../Core/Globals.js';
const { doc, win } = H;
```

So it seems that `doc` is being passed from `Globals.js` as `null` or `undefined`, which ultimately causes the issue

**Comment by karolkolodziej** [comment]
@gcko & @etrinh Thank you both for all your input! It's super valuable! 

Looks like the accessibility module worked correctly with Highcharts v11.1.0. 
We will take a closer look and try to find out what caused the issue.

**Comment by KacperMadej** [comment]
> Maybe it is stupid, but what about replacing root.document by root?.document on line 11?

That works. Good idea. I'm suggesting we do that.

_Internal note:_
@bre1470 Any ideas where could this be changed? I could only find scripts-esx but the code there doesn't match the build.

**Comment by bre1470** [comment]
@KacperMadej This is probably coming from the assembler: https://github.com/highcharts/highcharts-assembler/blob/master/src/templates/umd-standalone.txt

**Comment by hassanAlihafiz** [comment]
`const CustomPieChart = dynamic( () => import("@/components/common/custom-pie-chart/CustomPieChart"),{  ssr: false, });`

Calling the whole custom component dynamically fixed the issue for me.

Thanks to this guy: https://github.com/RaziUlH
It really helped me, thank you so much.

**Comment by Meow-Meow-afk** [comment]
getting issues like

Error: Highcharts error #17: www.highcharts.com/errors/17/?missingModuleFor=treegraph
 - missingModuleFor: treegraph

when i navigate to some page that contain the highchart code

but works fine when i just refresh that page
even with ssr:false in dynamic calling


any suggestions of fixes for this

PAGE COMPONENT

"use client";

import dynamic from "next/dynamic";
import { Suspense } from "react";

const Chart = dynamic(() => import("./Chart"), { ssr: false });

const page = () => {
  const dummyData = [
    ["", "root"], // root
    ["root", "A"],
    ["A", "B"],
    ["A", "C"],
    ["B", "D"],
    ["C", "E"],
    ["C", "F"],
  ].map(([parent, id]) => ({
    parent,
    id,
    name: id,
  }));

  return (
    <div className="w-full bg-dashboard py-4 px-4">
      <Suspense>
        <Chart chartData={dummyData} />
      </Suspense>
    </div>
  );
};

export default page;


CHART COMPONENT

"use client";

import Highcharts from "highcharts";
import "highcharts/modules/treemap";
import "highcharts/modules/treegraph";
import "highcharts/modules/accessibility";

import HighchartsReact from "highcharts-react-official";

const Chart = ({ chartData }: { chartData: any[] }) => {
  const options: Highcharts.Options = {
    chart: {
      inverted: true,
    },
    title: {
      text: "",
    },
    tooltip: {
      enabled: false,
    },
    series: [
      {
        type: "treegraph",
        data: chartData,
        marker: {
          enabled: true,
          symbol: "rect",
          width: 0,
          color: "red",
        },
        dataLabels: {
          formatter: function (this: any) {
            // If it's root node, return empty string to hide it
            if (this.id === "root") return "";

            // Always return the name, even if it's 0 or falsy
            return String(this.name);
          },
          style: {
            whiteSpace: "nowrap",
          },
        },
        link: {
          type: "curved",
          color: "#757575",
        },
        levels: [
          {
            level: 1,

            dataLabels: {
              enabled: false,
              style: {
                display: "none",
              },
            },
          },
          {
            level: 2,
            dataLabels: {
              style: {
                color: "#FFFFFF",
                textOutline: "none",
              },
              backgroundColor: "#0091FF",
              borderRadius: 4,
              padding: 6,
            },
            color: "#0091FF",
          },
          {
            level: 3,
            dataLabels: {
              style: {
                color: "#000000",
                textOutline: "none",
              },
              borderRadius: 4,
              padding: 6,
              backgroundColor: "#75F0E7",
            },
            color: "#75F0E7",
          },
          {
            level: 4,
            dataLabels: {
              backgroundColor: "#FFE4B3",
              style: {
                color: "#000000",
                textOutline: "none",
              },
              borderRadius: 4,
              padding: 6,
            },
            color: "#FFE4B3",
          },
          {
            level: 5,
            dataLabels: {
              backgroundColor: "#F4C0FF80",
              style: {
                color: "#000000",
                textOutline: "none",
              },
              borderRadius: 4,
              padding: 6,
            },
            color: "#F4C0FF80",
          },
        ],
      },
    ],
  };
  return <HighchartsReact highcharts={Highcharts} options={options} />;
};

export default Chart;

**Comment by KacperMadej** [comment]
Hi @Meow-Meow-afk 

Please contact technical support or open a new issue with clear steps for how to recreate the problem you have - live demo or an app are acceptable.

Poorly formatted code in a comment look more like spam than an actual question. Please fix your message formatting or even better - contact technical support first, and when reporting a bug post your code into a sandbox to share a live demo or an app, so the code could be tested and not only inspected.

If you are using `highcharts-react-official` then report an issue on its GitHub repository if it is not already reported - which might be the case depending on which version of the React integration you are using.
