### ISSUE TITLE
Project Management Gantt Expansion Rows 

### ISSUE THREAD

**Issue by BrendanRogers12** [highcharts/highcharts#20446]
#### Expected behaviour
Expansion rows open and close to view/hide dependencies

#### Actual behaviour
Expansion rows for Gantt Chart losing reference when closing and re-opening

Console Error: 
Uncaught TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at S (highcharts-gantt.js:8:1926)
    at Object.p (highcharts-gantt.js:8:372619)
    at t.<computed> (highcharts-gantt.js:8:8298)
    at Object.render (highcharts-gantt.js:8:75969)
    at Object.<anonymous> (highcharts-gantt.js:8:103591)
    at k (highcharts-gantt.js:8:1631)
    at highcharts-gantt.js:8:103558
    at Array.forEach (<anonymous>)
    at G.render (highcharts-gantt.js:8:103516)

#### Live demo with steps to reproduce
Code Example in Codepen: 
https://codepen.io/Brendan-Rogers-the-encoder/pen/PoLWLLe 

#### Affected browser(s)
Chrome

**Comment by BrendanRogers12** [comment]
my error - each element didnt have a uniqueId
