### ISSUE TITLE
Prebuilds are not available for Mac M2 (M series maybe?) tag `v11.3.0`

### ISSUE THREAD

**Issue by induratized** [highcharts/highcharts#20477]
#### Expected behaviour
`npm install` should install all dependencies and setup the npm project

#### Actual behaviour
`npm install` throws error in tag `v11.3.0`

#### Live demo with steps to reproduce
Use Mac M2 ARM to npm install 
System overview:
node `16.16.0`
npm `8.11.0`
OS: `Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:45 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6020 arm64`

<details>
  <summary><i>Click here to see npm error logs</i></summary>
 

>  npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
> npm WARN deprecated   npm i nyc
> npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
> npm ERR! code 1
> npm ERR! path /Users/abhinav.sharma/dev/highcharts/highcharts/node_modules/canvas
> npm ERR! command failed
> npm ERR! command sh -c node-pre-gyp install --fallback-to-build --update-binary
> npm ERR! Failed to execute '/Users/abhinav.sharma/.nvm/versions/node/v16.16.0/bin/node /Users/abhinav.sharma/.nvm/versions/node/v16.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/Users/abhinav.sharma/dev/highcharts/highcharts/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/abhinav.sharma/dev/highcharts/highcharts/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
> npm ERR! node-pre-gyp info it worked if it ends with ok
> npm ERR! node-pre-gyp info using node-pre-gyp@1.0.11
> npm ERR! node-pre-gyp info using node@16.16.0 | darwin | arm64
> npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v93-darwin-unknown-arm64.tar.gz
> npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v93-darwin-unknown-arm64.tar.gz 
> npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@16.16.0 (node-v93 ABI, unknown) (falling back to source compile with node-gyp) 
> npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v93-darwin-unknown-arm64.tar.gz 
> npm ERR! gyp info it worked if it ends with ok
> npm ERR! gyp info using node-gyp@9.0.0
> npm ERR! gyp info using node@16.16.0 | darwin | arm64
> npm ERR! gyp info ok 
> npm ERR! gyp info it worked if it ends with ok
> npm ERR! gyp info using node-gyp@9.0.0
> npm ERR! gyp info using node@16.16.0 | darwin | arm64
> npm ERR! gyp info find Python using Python version 3.9.6 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
> npm ERR! gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
> npm ERR! gyp info spawn args [
> npm ERR! gyp info spawn args   '/Users/abhinav.sharma/.nvm/versions/node/v16.16.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
> npm ERR! gyp info spawn args   'binding.gyp',
> npm ERR! gyp info spawn args   '-f',
> npm ERR! gyp info spawn args   'make',
> npm ERR! gyp info spawn args   '-I',
> npm ERR! gyp info spawn args   '/Users/abhinav.sharma/dev/highcharts/highcharts/node_modules/canvas/build/config.gypi',
> npm ERR! gyp info spawn args   '-I',
> npm ERR! gyp info spawn args   '/Users/abhinav.sharma/.nvm/versions/node/v16.16.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
> npm ERR! gyp info spawn args   '-I',
> npm ERR! gyp info spawn args   '/Users/abhinav.sharma/Library/Caches/node-gyp/16.16.0/include/node/common.gypi',
> npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
> npm ERR! gyp info spawn args   '-Dvisibility=default',
> npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/abhinav.sharma/Library/Caches/node-gyp/16.16.0',
> npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/abhinav.sharma/.nvm/versions/node/v16.16.0/lib/node_modules/npm/node_modules/node-gyp',
> npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/abhinav.sharma/Library/Caches/node-gyp/16.16.0/<(target_arch)/node.lib',
> npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/abhinav.sharma/dev/highcharts/highcharts/node_modules/canvas',
> npm ERR! gyp info spawn args   '-Dnode_engine=v8',
> npm ERR! gyp info spawn args   '--depth=.',
> npm ERR! gyp info spawn args   '--no-parallel',
> npm ERR! gyp info spawn args   '--generator-output',
> npm ERR! gyp info spawn args   'build',
> npm ERR! gyp info spawn args   '-Goutput_dir=.'
> npm ERR! gyp info spawn args ]
> npm ERR! /bin/sh: pkg-config: command not found
> npm ERR! gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
> npm ERR! gyp ERR! configure error 
> npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
> npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/Users/abhinav.sharma/.nvm/versions/node/v16.16.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:261:16)
> npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
> npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
> npm ERR! gyp ERR! System Darwin 23.1.0
> npm ERR! gyp ERR! command "/Users/abhinav.sharma/.nvm/versions/node/v16.16.0/bin/node" "/Users/abhinav.sharma/.nvm/versions/node/v16.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--update-binary" "--module=/Users/abhinav.sharma/dev/highcharts/highcharts/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/Users/abhinav.sharma/dev/highcharts/highcharts/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
> npm ERR! gyp ERR! cwd /Users/abhinav.sharma/dev/highcharts/highcharts/node_modules/canvas
> npm ERR! gyp ERR! node -v v16.16.0
> npm ERR! gyp ERR! node-gyp -v v9.0.0
> npm ERR! gyp ERR! not ok 
> npm ERR! node-pre-gyp ERR! build error 
> npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/Users/abhinav.sharma/.nvm/versions/node/v16.16.0/bin/node /Users/abhinav.sharma/.nvm/versions/node/v16.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/Users/abhinav.sharma/dev/highcharts/highcharts/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/abhinav.sharma/dev/highcharts/highcharts/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
> npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/abhinav.sharma/dev/highcharts/highcharts/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
> npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
> npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
> npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
> npm ERR! node-pre-gyp ERR! System Darwin 23.1.0
> npm ERR! node-pre-gyp ERR! command "/Users/abhinav.sharma/.nvm/versions/node/v16.16.0/bin/node" "/Users/abhinav.sharma/dev/highcharts/highcharts/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
> npm ERR! node-pre-gyp ERR! cwd /Users/abhinav.sharma/dev/highcharts/highcharts/node_modules/canvas
> npm ERR! node-pre-gyp ERR! node -v v16.16.0
> npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.11
> npm ERR! node-pre-gyp ERR! not ok

</details>

**Comment by induratized** [comment]
I dug it some and found this node-canvas issue [link](https://github.com/Automattic/node-canvas/issues/1825) which asked us to follow this [guide](https://github.com/Automattic/node-canvas/wiki#installation-guides) suggesting to install prebuilds via brew as below
`brew install pkg-config cairo pango libpng jpeg giflib librsvg`

The `npm install` was successful after that BUT I need to confirm it was correct to do so or provide any suggestion to improve the guide provided above

**Comment by karolkolodziej** [comment]
Hi @induratized! 

You are right the command can be used as a workaround to set up the library.
@goransle You've investigated the issue, is there anything we can do about it?

**Comment by induratized** [comment]
> I can confirm that these packages are required for our tooling to work. 
> 
> However, if you are looking for precompiled files I would suggest having a look at the [highcharts-dist](https://github.com/highcharts/highcharts-dist) repository (or the `highcharts` npm package).

I was trying to build highcharts custom packages to reduce the size of the lib for my use case which required setting up the project.

Thanks for your quick update, my project is setup and I saved ~100kb via custom package build

**Comment by induratized** [comment]
linked issue after custom build was success: #20503
