### ISSUE TITLE
Custom package build js throws `Uncaught ReferenceError: exports is not defined`

### ISSUE THREAD

**Issue by induratized** [highcharts/highcharts#20503]
#### Expected behaviour
Custom package should run without errors in browser
**tag**: `v11.3.0`
custom package build instruction followed from [here](https://www.highcharts.com/docs/getting-started/how-to-create-custom-highcharts-packages)

#### Actual behaviour
Custom package throws error as below

> custom.js:8 Uncaught ReferenceError: exports is not defined
>     at custom.js:8:183652
>     at i (custom.js:7:386)
>     at custom.js:8:183421
>     at custom.js:7:257
>     at custom.js:7:263

<details>
  <summary>error on LOC screenshot</summary>
<img width="1056" alt="image" src="https://github.com/highcharts/highcharts/assets/6311837/5a985f10-30ca-42ca-9795-eff06119215e">

</details>

#### Live demo with steps to reproduce
<details>
  <summary>custom master file: ts/masters/custom.src.**ts**</summary>

```javascript
'use strict';
import Highcharts from '../Core/Globals.js';
import SVGRenderer from '../Core/Renderer/SVG/SVGRenderer.js';
import Chart from '../Core/Chart/Chart.js';
import ColumnSeries from '../Series/Column/ColumnSeries.js';
import LineSeries from '../Series/Line/LineSeries.js';
import PieSeries from '../Series/Pie/PieSeries.js';
const exports: Record<string, any> = Highcharts;
exports.Renderer = SVGRenderer;
exports.SVGRenderer = SVGRenderer;
exports.Chart = Chart;
exports.chart = Chart.chart;
exports.ColumnSeries = ColumnSeries;
exports.LineSeries = LineSeries;
exports.PieSeries = PieSeries;
export default Highcharts;
```

</details>

**node**: v`16.16.0`
**npm** : `8.11.0`

Custom built file attached below: code/custom.src.**js**
[custom.src.js.docx](https://github.com/highcharts/highcharts/files/14022957/custom.src.js.docx)

#### Product version
highcharts: tag: v`11.3.0`

#### Affected browser(s)
All browsers

Please let me know how to fix this, there is no instructions given in the doc regarding this.
Do we need another module loader package like SystemJS AMD etc for this?
Is there any other to target specific build format like commonjs , iife?

**Comment by karolkolodziej** [comment]
Hi @induratized!

I copied your `custom.src.ts` file and I ran the bundling with `npx gulp scripts --force` and `npx gulp scripts-compile`.

But on my end, everything compiles and works in the demo correctly (except for some missing tooltip methods but I definitely can see the chart). I use an Apple M1 Pro chip. 

The only difference is that I've used the node in version `v18.18.0`. Otherwise, I wasn't able to run it.
Please try a different node version and let me know if you still get this error.

**Comment by induratized** [comment]
Hi @karolkolodziej 

I tried compiling custom build with same `masters/custom.src.ts` file with..

**node**: `v18.18.0`
**npm**: `v9.8.1`

.. and still I got the same error, screenshot attached below,
<img width="1512" alt="image" src="https://github.com/highcharts/highcharts/assets/6311837/50efe6f6-c35a-4358-a1ee-7b1da7534101">

my device: Apple M2 Pro [OS v14.1.1 (23B81)]

I have created a [jsfiddle](https://jsfiddle.net/zj94erat/2/) to reproduce the issue, the same code runs fine with highcharts full lib but doesnt with my custom build js file

**Comment by karolkolodziej** [comment]
Your code:
```js
    _registerModule(_modules, 'masters/custom.src.js', [_modules['Core/Globals.js'], _modules['Core/Renderer/SVG/SVGRenderer.js'], _modules['Core/Chart/Chart.js'], _modules['Series/Column/ColumnSeries.js'], _modules['Series/Line/LineSeries.js'], _modules['Series/Pie/PieSeries.js']], function (Highcharts, SVGRenderer, Chart, ColumnSeries, LineSeries, PieSeries) {

        // // const exports = Highcharts;
        exports.Renderer = SVGRenderer;
        exports.SVGRenderer = SVGRenderer;
        exports.Chart = Chart;
        exports.chart = Chart.chart;
        // exports.BarSeries = BarSeries;
        exports.ColumnSeries = ColumnSeries;
        exports.LineSeries = LineSeries;
        exports.PieSeries = PieSeries;
        // exports.AreaSplineSeries = AreaSplineSeries;

        return Highcharts;
    });
```
mine:
```js
    _registerModule(_modules, 'masters/custom.src.js', [_modules['Core/Globals.js'], _modules['Core/Renderer/SVG/SVGRenderer.js'], _modules['Core/Chart/Chart.js'], _modules['Series/Column/ColumnSeries.js'], _modules['Series/Line/LineSeries.js'], _modules['Series/Pie/PieSeries.js']], function (Highcharts, SVGRenderer, Chart, ColumnSeries, LineSeries, PieSeries) {

        const exports = Highcharts;
        exports.Renderer = SVGRenderer;
        exports.SVGRenderer = SVGRenderer;
        exports.Chart = Chart;
        exports.chart = Chart.chart;
        exports.ColumnSeries = ColumnSeries;
        exports.LineSeries = LineSeries;
        exports.PieSeries = PieSeries;

        return Highcharts;
    });
```

Did you comment that out or is it the outcome of the bundling process?
