### ISSUE TITLE
Can´t download a png exported image when so many data

### ISSUE THREAD

**Issue by Pedrooacc** [highcharts/highcharts#20657]
#### Expected behaviour
I want to download a png of my chart when i have +10 lines with data on it.

#### Actual behaviour
Got this error, and I don't have node.js on my project ->
MulterError: Field value too long
    at abortWithCode (/var/app/current/node_modules/multer/lib/make-middleware.js:71:22)
    at Multipart.<anonymous> (/var/app/current/node_modules/multer/lib/make-middleware.js:78:34)
    at Multipart.emit (node:events:517:28)
    at SBMH.ssCb [as _cb] (/var/app/current/node_modules/busboy/lib/types/multipart.js:537:16)
    at feed (/var/app/current/node_modules/streamsearch/lib/sbmh.js:219:14)
    at SBMH.push (/var/app/current/node_modules/streamsearch/lib/sbmh.js:104:16)
    at Multipart._write (/var/app/current/node_modules/busboy/lib/types/multipart.js:567:19)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)

#### Product version
11.2.0
#### Affected browser(s)
Everyone

**Comment by Pedrooacc** [comment]
Hi @karolkolodziej! 
Of course, in [this example](https://jsfiddle.net/9j3y1mt2/) I can´t download a png, the code error don't come out because its not a web page but I think it will help you.

**Comment by jakubSzuminski** [comment]
It's likely that this has been fixed with this commit: https://github.com/highcharts/node-export-server/pull/482/commits/0e0a8729e01123df6070f9e2a4baf00ad703a830 which will be a part of the 4.0.0 version which is the next upcoming release.

**Comment by jszuminski** [comment]
Hi, we have not released v4.0.0 of the Export Server yet (so the Multer-related problem has not yet been solved on the currently deployed export.highcharts.com site).

**Comment by ROCarrera** [comment]
Nothing about this deploy yet?

**Comment by jszuminski** [comment]
We've scheduled a deploy of the Export Server v4.0.0 for next week so it should be fixed by the end of the next week.
