### ISSUE TITLE
Dashboards: Cannot leave edit mode after removing cell

### ISSUE THREAD

**Issue by stitot** [highcharts/highcharts#20688]
Reported by potential customer

#### Expected behaviour
Edit mode is disabled.

#### Actual behaviour
Edit mode stays active, exception in the browser’s console:

```
Uncaught TypeError: Cannot read properties of undefined (reading
'setHighlight')
at Object.deactivate (dashboards.js:9:71454)
at Object.onEditModeToggle (dashboards.js:9:68818)
at n.click (dashboards.js:9:53499)
at HTMLButtonElement.<anonymous> (dashboards.js:9:14723)
```

#### Steps to reproduce
- Enable edit mode via the “burger menu” on the top right.
- Select any cell by clicking on it.
- Remove the selected cell by clicking on the trash bin icon and then confirm to destroy
the cell.
- Try to disable edit mode again via the “burger menu” on the top right.
- 
#### Product version
Observed at https://www.highcharts.com/demo

#### Affected browser(s)
All

**Comment by karolkolodziej** [comment]
[Simplified demo with v1 where I can recreate the issue.](https://jsfiddle.net/BlackLabel/p9Lvmsxg/)

**Comment by karolkolodziej** [comment]
@stitot What should happen when the cell gets removed?
Is current behaviour (no other cell/row is highlighted) ok?

**Comment by stitot** [comment]
@karolkolodziej : yes, let's keep current behavior for this bugfix. We could look at some logic where adjacent cell(s) get expanded to fill the gap, but that's a separate issue.
