### ISSUE TITLE
ERROR TypeError: Cannot read properties of undefined (reading 'forExport')

### ISSUE THREAD

**Issue by bskemp01** [highcharts/highcharts#20921]
Here is a stackblitz of my app: [Inventory app](https://stackblitz.com/~/github.com/bskemp01/inventory)

also here is a video of the error: [Video of Error](https://youtu.be/5J559-dzfhk)

basically when i click on a category to view a single location and then make any sort of navigation to another component/page i get this error:

`ERROR TypeError: Cannot read properties of undefined (reading 'forExport')
    at Q.destroy (highcharts.js:8:209410)
    at HighchartsChartComponent.ngOnDestroy (highcharts-angular.mjs:43:24)
    at executeOnDestroys (core.mjs:9960:32)
    at cleanUpView (core.mjs:9863:9)
    at destroyViewTree (core.mjs:9691:21)
    at destroyLView (core.mjs:9836:9)
    at ViewRef$1.destroy (core.mjs:12672:9)
    at ComponentRef.destroy (core.mjs:15462:23)
    at RouterOutlet.deactivate (router.mjs:2544:28)
    at ActivateRoutes.deactivateRouteAndOutlet (router.mjs:3065:32)`

**i have tried implementing some other solutions from other who have posted about this error but to no avail i cannot get around this error. my hopes is that someone will see my code and find out the problem. Please ask if you have any questions. thanks**

**Comment by bskemp01** [comment]
> Hi @bskemp01! A similar issue was reported in the `highcharts-angular` repo- [see](https://github.com/highcharts/highcharts-angular/issues/231).
> 
> The issue is that initially, you render the chart as a `highcharts-chart` component from the `highcharts-angular` repo and later on, in the same element, you overwrite it with a vanilla Highcharts instance by:
> 
> ```ts
>   private redrawChart() {
>     const chart = Highcharts.chart('columnChart', this.chartOptions);
>     chart.reflow();
>   }
> ```
> 
> To avoid errors, choose one approach and ensure that the instances are destroyed when changing routes. If you still struggle with it please see the examples in the thread I've linked above or contact [our support team.](https://www.highcharts.com/blog/support/)

hello Karol. i see now my mistake. it was as simple as changing:

`private redrawChart() {
    const chart = Highcharts.chart('columnChart', this.chartOptions);
    chart.reflow();
  }`
  
  To:

`private redrawChart() {
    this.updateFlag = true;
  }`
