### ISSUE TITLE
TypeError: can't access property "stacks", this.waterfall is undefined

### ISSUE THREAD

**Issue by Tommaso-FLYR** [highcharts/highcharts#21276]
#### Expected behaviour

No type error

#### Actual behaviour

Firefox
```
TypeError: can't access property "stacks", this.waterfall is undefined
    i highcharts-more.js:7
    C highstock.js:8
    C highstock.js:8
    buildStacks highstock.js:8
    setScale highstock.js:8
    setSize highstock.js:8
```

Chrome
```
TypeError: Cannot read properties of undefined (reading 'stacks')
    at G.i (highcharts-more.js:7:1)
    at highstock.js:8:1
    at Array.forEach (<anonymous>)
    at C (highstock.js:8:1)
    at A.buildStacks (highstock.js:8:1)
    at G.setScale (highstock.js:8:1)
    at highstock.js:8:1
    at Array.forEach (<anonymous>)
    at Q.setSize (highstock.js:8:1)
    at highstock.js:8:1
```

#### Live demo with steps to reproduce

I'm not able to make a minimal reproduction of this error, and it doesn't seem like there's anything broken in the chart itself, I suppose it's only a matter of handling the `undefined` case

#### Product version
"highcharts": "11.4.3",
"highcharts-react-official": "3.2.1",

#### Affected browser(s)

Firefox 127.0b9 (64-bit)
Chrome 125.0.6422.142 (Official Build) (arm64)

**Comment by karolkolodziej** [comment]
Hi @Tommaso-FLYR! 
Could you please guide me on how to recreate that because I was not able to [see the demo.](https://stackblitz.com/edit/highcharts-angular-line-qifzah?file=src%2Fapp%2Fapp.component.ts)

You can modify the demo linked above.

**Comment by saurabhgang21** [comment]
Hi @karolkolodziej 

Even I am faxing the same error. this.waterfall is undefined because of that it fails sometimes.

**Comment by karolkolodziej** [comment]
@saurabhgang21 how do you import all the modules?

**Comment by saver711** [comment]
@karolkolodziej Iam facing same problem

Inside Nextjs application
here is my component code
`
'use client';
import Dashboards from '@highcharts/dashboards';
import '@highcharts/dashboards/css/dashboards.css';
import '@highcharts/dashboards/css/datagrid.css';
import DataGrid from '@highcharts/dashboards/datagrid';
import Highcharts from 'highcharts';
import { Box, Grid } from '@mui/material';
import { useEffect, useRef } from 'react';

import { DASHBOARD_CONFIG } from './dashboard-config.const';

if (typeof window !== 'undefined' && typeof Highcharts === 'object') {
	Dashboards.HighchartsPlugin.custom.connectHighcharts(Highcharts);
	Dashboards.DataGridPlugin.custom.connectDataGrid(DataGrid);
	Dashboards.PluginHandler.addPlugin(Dashboards.HighchartsPlugin);
	Dashboards.PluginHandler.addPlugin(Dashboards.DataGridPlugin);
}

export const Dashboard = () => {
	const hasEffectRun = useRef(false);

	useEffect(() => {
		if (hasEffectRun.current) return;
		hasEffectRun.current = true;
		Dashboards.board('container', DASHBOARD_CONFIG);
	}, []);

	return (
		<>
			<Box id='container'>
				<Grid container spacing={2}>
					<Grid item xs={6}>
						<Box id='dashboard-col-0' />
					</Grid>
					<Grid item xs={12}>
						<Box id='dashboard-col-2' />
					</Grid>
				</Grid>
			</Box>
		</>
	);
};

`


here is my config
`
export const DASHBOARD_CONFIG: Dashboards.Board.Options = {
	dataPool: {
		connectors: [
			{
				id: 'micro-element',
				type: 'JSON',
				options: {
					firstRowAsNames: false,
					columnNames: ['Food', 'Vitamin A', 'Iron'],
					data: [
						['Beef Liver', 6421, 6.5],
						['Lamb Liver', 2122, 6.5],
						['Cod Liver Oil', 1350, 0.9],
						['Mackerel', 388, 1],
						['Tuna', 214, 0.6],
					],
				},
			},
		],
	},
	gui: { enabled: false, layouts: [] },
	components: [
		{
			sync: {
				visibility: true,
				highlight: true,
				extremes: true,
			},
			connector: {
				id: 'micro-element',
				columnAssignment: [
					{
						seriesId: 'Vitamin A',
						data: ['Food', 'Vitamin A'],
					},
				],
			},
			// cell: 'dashboard-col-0',
			renderTo: 'dashboard-col-0',
			type: 'Highcharts',
			columnAssignment: {
				Food: 'x',
				'Vitamin A': 'value',
			},
			chartOptions: {
				xAxis: {
					type: 'category',
					accessibility: {
						description: 'Groceries',
					},
				},
				credits: {
					enabled: false,
				},
				plotOptions: {
					series: {
						marker: {
							radius: 6,
						},
					},
				},
				legend: {
					enabled: true,
					verticalAlign: 'top',
				},
				chart: {
					animation: false,
					type: 'column',
					spacing: [30, 30, 30, 20],
				},
				title: {
					text: '',
				},
				tooltip: {
					valueSuffix: ' mcg',
					stickOnContact: true,
				},
				lang: {
					accessibility: {
						chartContainerLabel: 'Vitamin A in food. Highcharts Interactive Chart.',
					},
				},
				accessibility: {
					description: `The chart is displaying the Vitamin A amount in
                  micrograms for some groceries. There is a plotLine demonstrating
                  the daily Recommended Dietary Allowance (RDA) of 900
                  micrograms.`,
					point: {
						valueSuffix: ' mcg',
					},
				},
			},
		},
		{
			// cell: 'dashboard-col-2',
			renderTo: 'dashboard-col-2',
			connector: {
				id: 'micro-element',
			},
			type: 'DataGrid',
			sync: {
				highlight: true,
				visibility: true,
			},
			dataGridOptions: {
				credits: {
					enabled: false,
				},
			},
		},
	],
};

`
When i try to click on this legend

<img width="1241" alt="Image" src="https://github.com/user-attachments/assets/9c8d17de-34e6-4d25-8daa-b38a528c862e" />

i get same error

NOTE:

I **can not** import modules (Specially layout module at the top of my component file)
`import '@highcharts/dashboards/modules/layout';`

as i get this error:

<img width="969" alt="Image" src="https://github.com/user-attachments/assets/ec04eea8-4ec1-4f33-bc5c-1e3aa00891ab" />

**Comment by karolkolodziej** [comment]
Hi @saver711
I've tested your code locally, and I cannot reproduce it. Clicking on the legend changes the visibility of the series without error:

![Image](https://github.com/user-attachments/assets/6598d839-83b5-465c-bc1a-101d3974195d)


When it comes to loading the `layout` module, I was able to see the same error, and its probably related to how the Next.js loads all of the scripts.
In Next.js, we recommend using ESM imports like:
```
import Dashboards from '@highcharts/dashboards/es-modules/masters/dashboards.src.js';
import '@highcharts/dashboards/es-modules/masters/modules/layout.src.js';
```

**Comment by karolkolodziej** [comment]
Here is how my file looks like:
```tsx
'use client';
import Dashboards from '@highcharts/dashboards/es-modules/masters/dashboards.src.js';
import '@highcharts/dashboards/es-modules/masters/modules/layout.src.js';
import DataGrid from '@highcharts/dashboards/datagrid';
import Highcharts from 'highcharts';
import { useEffect, useRef } from 'react';

if (typeof window !== 'undefined' && typeof Highcharts === 'object') {
    Dashboards.HighchartsPlugin.custom.connectHighcharts(Highcharts);
    Dashboards.DataGridPlugin.custom.connectDataGrid(DataGrid);
    Dashboards.PluginHandler.addPlugin(Dashboards.HighchartsPlugin);
    Dashboards.PluginHandler.addPlugin(Dashboards.DataGridPlugin);
}

const DASHBOARD_CONFIG = {
    dataPool: {
        connectors: [
            {
                id: 'micro-element',
                type: 'JSON',
                options: {
                    firstRowAsNames: false,
                    columnNames: ['Food', 'Vitamin A', 'Iron'],
                    data: [
                        ['Beef Liver', 6421, 6.5],
                        ['Lamb Liver', 2122, 6.5],
                        ['Cod Liver Oil', 1350, 0.9],
                        ['Mackerel', 388, 1],
                        ['Tuna', 214, 0.6]
                    ]
                }
            }
        ]
    },
    gui: {
        layouts: [{
            id: 'layout-1',
            rows: [{
                cells: [
                    { id: 'dashboard-col-0' },
                    { id: 'dashboard-col-2' }
                ]
            }]
        }]
    },
    components: [
        {
            sync: { visibility: true, highlight: true, extremes: true },
            connector: {
                id: 'micro-element',
                columnAssignment: [{ seriesId: 'Vitamin A', data: ['Food', 'Vitamin A'] }]
            },
            renderTo: 'dashboard-col-0',
            type: 'Highcharts',
            columnAssignment: { Food: 'x', 'Vitamin A': 'value' },
            chartOptions: {
                xAxis: { type: 'category', accessibility: { description: 'Groceries' } },
                credits: { enabled: false },
                plotOptions: { series: { marker: { radius: 6 } } },
                legend: { enabled: true, verticalAlign: 'top' },
                chart: { animation: false, type: 'column', spacing: [30, 30, 30, 20] },
                title: { text: '' },
                tooltip: { valueSuffix: ' mcg', stickOnContact: true }
            }
        },
        {
            renderTo: 'dashboard-col-2',
            connector: {
                id: 'micro-element'
            },
            type: 'DataGrid',
            sync: {
                highlight: true,
                visibility: true
            },
            dataGridOptions: {
                credits: {
                    enabled: false
                }
            }
        }
    ]
};

export default function Home() {
    const hasEffectRun = useRef(false);

    useEffect(() => {
        if (hasEffectRun.current) return;
        hasEffectRun.current = true;
        Dashboards.board('container', DASHBOARD_CONFIG);
    }, []);

    return <div id="container" />;
}
```
