### ISSUE TITLE
Regression between 11.4.1 and 11.4.3 causing TypeError: Cannot read properties of null (reading 'length')

### ISSUE THREAD

**Issue by FourSeventy** [highcharts/highcharts#21707]
#### Expected behaviour
I have a bar chart rendered with some data. When I redraw the chart with a new dataset it throws a bunch of the below error into the console. It throws one error per bar in the bar chart.

Error in console:
TypeError: Cannot read properties of null (reading 'length')
    at erase (highcharts.js:8:1)
    at h.destroy (highcharts.js:8:1)
    at h.destroy (highcharts.js:8:1)
    at highcharts.js:8:1
    at Array.forEach (<anonymous>)
    at k.destroyElements (highcharts.js:8:1)
    at a (highcharts.js:8:1)

This is a regression in 11.4.3. The issue does not exist in 11.4.1.

If I had to guess I think that this is the commit that caused the issue: https://github.com/highcharts/highcharts/pull/20994/files

#### Actual behaviour
No errors thrown in console when bar chart re-rendered.

#### Live demo with steps to reproduce
I don't have a jsfiddle but I have a video of it happening: https://www.loom.com/share/4cb664a61708470b8c7f40cea09f8451?sid=6e4a9702-1efc-486f-9e55-5b10825e027f

And here is a gist containing the highcharts config: https://gist.github.com/FourSeventy/b936c2fc03f0b5a7f5785132b7f52533

#### Product version
11.4.3 has the issue
11.4.1 is fine

**Comment by hubertkozik** [comment]
Hi @FourSeventy! I was trying to reproduce your issue here: https://jsfiddle.net/BlackLabel/p74moqbg/ based on the code you provided but after changing the series dataset, everything is working correctly. I also checked it in Highcharts v11.4.3 and it is working correctly. 

I'm afraid without a straight reproduction of the issue in an online editor, e.g. JSFiddle I won't be able to help you. Could you reproduce the issue in an online editor that I could work on? You can use my demo and send me a link to the forked demo.

Also, can you check if the issue exists in your projection with the latest version of Highcharts, which is Highcharts v11.4.7?
