### ISSUE TITLE
Uncaught TypeError When Resizing Funnel Chart

### ISSUE THREAD

**Issue by alexd99** [highcharts/highcharts#21814]
#### Expected behaviour
When I resize a funnel chart from a large window to a small window and then back to a large window, I would expect the chart to dynamically change with out any errors.

#### Actual behaviour
I get an `Uncaught TypeError`, and the chart remains the size it was when the window was small.

```text
funnel.js:9 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at S.translate (funnel.js:9:2565)
    at S.redraw (highcharts.js:8:172328)
    at highcharts.js:8:199852
    at Array.forEach (<anonymous>)
    at Q.redraw (highcharts.js:8:199803)
    at Q.setSize (highcharts.js:8:206366)
    at highcharts.js:8:205492
```

#### Live demo with steps to reproduce
https://jsfiddle.net/80co3yv2/

- Resize the window with the sales funnel to a smaller width, until the the chart has inverted it's top and bottom width's
- Resize the window to a larger width
- The chart will remain in the small state, and an error will appear in the console 

#### Product version
Highcharts JS v11.4.8 (2024-08-29)

#### Affected browser(s)
Chrome 128.0.6613.120

**Comment by hubertkozik** [comment]
Hi @alexd99! Thank you for reporting the issue. Here's the simplified demo: https://jsfiddle.net/BlackLabel/0h92tLj1/

It looks like a regression, the last working version was Highcharts v10.3.3.

As a workaround, you can set the plot options specifically for funnel series instead of all series.
**OP demo with a workaround:** https://jsfiddle.net/BlackLabel/Lnthqwxy/
**Simplified demo with a workaround:** https://jsfiddle.net/BlackLabel/g85wemf2/
