### ISSUE TITLE
Cannot read properties of undefined (reading 'SVGElement')

### ISSUE THREAD

**Issue by arunmmanoharan** [highcharts/highcharts#22315]
#### Expected behaviour
Should compile

#### Actual behaviour
Cannot read properties of undefined (reading 'SVGElement') when importing networkGraph

TypeError: Cannot read properties of undefined (reading 'SVGElement')
    at /Users/arunmmanoharan/mdm-azure-remix/node_modules/.pnpm/highcharts@12.0.2/node_modules/highcharts/modules/networkgraph.js:11:113
    at Object.<anonymous> (/Users/arunmmanoharan/mdm-azure-remix/node_modules/.pnpm/highcharts@12.0.2/node_modules/highcharts/modules/networkgraph.js:11:535)

#### Live demo with steps to reproduce

https://stackblitz.com/edit/vitejs-vite-kgbkbjc2?file=src%2FApp.tsx&terminal=dev

Please see the console. All I did was to import.

**Comment by karolkolodziej** [comment]
Hi @arunmmanoharan!
I'm not an expert in Vite but I think it is related to the way TS code is being bundled.

A couple of observations:
1. It works in Vite with JS- [demo](https://stackblitz.com/edit/vitejs-vite-ubbligfp?file=src%2FApp.jsx&terminal=dev).
2. Works correctly with ESM- [demo](https://stackblitz.com/edit/vitejs-vite-vzswxqhb?file=src%2FApp.tsx&terminal=dev). Which is what I believe is the recommended way in Vite
```ts
import 'highcharts/es-modules/masters/highcharts.src';
import 'highcharts/es-modules/masters/highcharts-more.src';
```

**Comment by TorsteinHonsi** [comment]
Another observation, Highcharts + networkgraph works. Vite, no React: https://stackblitz.com/edit/vitejs-vite-kcqa2zpd?file=src%2Fmain.js,package.json

**Comment by arunmmanoharan** [comment]
It works in React + JS. TS is what gives the error. @karolkolodziej  @TorsteinHonsi  Can either of you help me with a React + TS example?

**Comment by karolkolodziej** [comment]
@arunmmanoharan If you use ESM in the React + TS it works-[ see in the demo.](https://stackblitz.com/edit/vitejs-vite-qmmtkjf5?file=src%2FApp.tsx&terminal=dev)

**Comment by goransle** [comment]
This is partially due to the `Highcharts` import getting cleaned by being unused. Using it somehow, makes it available for the module: https://stackblitz.com/edit/vitejs-vite-nmre9ylk?file=src%2FApp.tsx&terminal=dev

Alternatively, adding `"verbatimModuleSyntax": true` to `compilerOptions` in `tsconfig.json` prevents it being cleaned up: https://stackblitz.com/edit/vitejs-vite-tqk95otg?file=tsconfig.app.json&terminal=dev
