### ISSUE TITLE
Error 'Cannot destructure property 'cache' of undefined' at afterSetExtremes on datetime axis with formatting list 

### ISSUE THREAD

**Issue by KseniaD0x0** [highcharts/highcharts#22363]
I'm trying to implement dynamic step change for axis ticks. To do so I subscribe on afterSetExtremes event on xAxis and adjust the step when needed. It works fine in most cases but with certain data points and with certain width of the chart (has to be around 1200px) labels start to disappear and I see the following error:

Uncaught TypeError: Cannot destructure property 'cache' of 'h' as it is undefined.
    at eq.getBBox (highstock.js:9:38598)
    at t.shortenLabel (highstock.js:9:72064)
    at sj.<anonymous> (highstock.js:9:96997)
    at Array.forEach (<anonymous>)
    at sj.renderUnsquish (highstock.js:9:96907)
    at sj.getOffset (highstock.js:9:98883)
    at highstock.js:9:205061
    at Array.forEach (<anonymous>)
    at o (highstock.js:9:205028)
    at cK.getAxisMargins (highstock.js:9:205097)

Seems like it is somehow related to the labels format list used with afterSetExtremes event. Without any of them the issue does not reproduce on the same data.

#### Live demo with steps to reproduce
[Fiddle](https://jsfiddle.net/stealkvas/7rmLtuok/1/)

1. Expand the chart to around 1200px wide 
2. Zoom in with mouse wheel until labels disappear and there are errors in the console. At this point seems like axis is broken, as it stops adjusting for the width of the parent container as well.

#### Product version
Latest

#### Affected browser(s)
tested in Chrome

**Comment by bm64** [comment]
Hello @KseniaD0x0 and thanks for reporting the issue.

As a workaround try overwriting `addLabel` function: https://jsfiddle.net/BlackLabel/846damho/

**Comment by KseniaD0x0** [comment]
Hi @bm64 , thank you for the suggestion. The error is gone, but looks like it loses formatting options at some point. 
![image](https://github.com/user-attachments/assets/118b72c2-b739-4bbb-82bf-1873c5cf8cd7)
