### ISSUE TITLE
V4.2.7 has breaking changes when used with highcharts-export-clientside

### ISSUE THREAD

**Issue by PavaniKa** [highcharts/highcharts#5717]
https://github.com/A----/highcharts-export-clientside/issues/36

Hi,

We are using this module in our applications. This has an internal dependency on 'highcharts' https://github.com/highcharts/highcharts-dist/ module. Today (09/21/2016) a new version v4.2.7 of highcharts is released. With the new version it is breaking the code internally. Below is the exact error.
```
jQuery.Deferred exception: Cannot read property 'drilldown' of null TypeError: Cannot read property 'drilldown' of null
    at http://localhost:6015/bower_components/highcharts/modules/drilldown.js:15:110
    at Array.forEach (native)
    at q (http://localhost:6015/bower_components/highcharts/highcharts.js:26:277)
    at Object.d.Axis.getDDPoints (http://localhost:6015/bower_components/highcharts/modules/drilldown.js:15:4)
    at Object.x.drillable (http://localhost:6015/bower_components/highcharts/modules/drilldown.js:15:273)
    at Object.<anonymous> (http://localhost:6015/bower_components/highcharts/modules/drilldown.js:16:139)
    at Object.a.(anonymous function) (http://localhost:6015/bower_components/highcharts/highcharts.js:22:244)
    at Object.<anonymous> (http://localhost:6015/js/Highcharts/plugins/customEvents.js:213:34)
    at Object.a.(anonymous function) [as addLabel] (http://localhost:6015/bower_components/highcharts/highcharts.js:22:244)
    at Object.Ya (http://localhost:6015/bower_components/highcharts/highcharts.js:15:102) undefined
```
As a workaround, we are explicitly installing the previous version of highcharts v.4.2.6.

old bower.json file was looking like...
```
"dependencies": {
    "bootstrap": "^3.3.6",
    "highcharts-export-clientside": "^1.1.4"
  }
```
To fix the issue, we mentioned the exact highcharts version
```
"dependencies": {
    "bootstrap": "^3.3.6",
    "highcharts": "4.2.6",
    "highcharts-export-clientside": "^1.1.4"
  }
```
Just wanted to bring this to your attention.

Thanks in advance.

**Comment by oysteinmoseng** [comment]
Hi, this exporting module is not provided nor supported by us, so any errors would have to be reported to the creator of the module.

We do however have an [official module](http://www.highcharts.com/docs/export-module/client-side-export) for client side exporting.
