### ISSUE TITLE
Regression between 5.0.9 and 5.0.10 - highmaps not displayed -  Cannot read property 'destroy' of null

### ISSUE THREAD

**Issue by npetralia** [highcharts/highcharts#6632]
Hello,

I found a bug on Highmaps, the map is not displayed.

#### Expected behaviour
To be able to display a Map

#### Actual behaviour
Map not displayed and error on JS console:

angular.js:14199 TypeError: Cannot read property 'destroy' of null
    at https://code.highcharts.com/maps/5.0.10/modules/map.js:20:245
    at Array.forEach (native)
    at a.each (https://code.highcharts.com/5.0.10/highcharts.js:26:471)
    at a.ColorAxis.update (https://code.highcharts.com/maps/5.0.10/modules/map.js:20:192)
    at a.Chart.<anonymous> (https://code.highcharts.com/5.0.10/highcharts.js:324:6)
    at Array.forEach (native)
    at a.each (https://code.highcharts.com/5.0.10/highcharts.js:26:471)
    at a.Chart.<anonymous> (https://code.highcharts.com/5.0.10/highcharts.js:323:435)
    at Array.forEach (native)
    at a.each (https://code.highcharts.com/5.0.10/highcharts.js:26:471)

#### Live demo with steps to reproduce
http://jsfiddle.net/4hg19x58/

If you change <script src="https://code.highcharts.com/5.0.10/highcharts.js"></script> to <script src="https://code.highcharts.com/5.0.9/highcharts.js"></script> it will work correctly.

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @npetralia 

Thank you for reporting the issue!

**Workaround:**
Set `colorAxis` as an array of objects, instead of an object. Additionally, set `gridLineWidth` to zero. Demo: http://jsfiddle.net/4hg19x58/2/

**Comment by TorsteinHonsi** [comment]
@pawelfus Do you have more details? Without angular it works: http://jsfiddle.net/highcharts/d3ddfxv3/2/

**Comment by pawelfus** [comment]
It's caused by using `chart.update()`, minified demo: http://jsfiddle.net/d3ddfxv3/3/

**Comment by TorsteinHonsi** [comment]
Fails since ca99aecc9. Prior to that, colorAxis wasn't handled at all from `chart.update`.
