### ISSUE TITLE
Histogram can't take function as binsNumber argument

### ISSUE THREAD

**Issue by Munksgaard** [highcharts/highcharts#7457]
#### Expected behaviour

Passing a function as the binsNumber argument to a histogram chart uses that function to compute the number of bins to show.

#### Actual behaviour

The following error is thrown (in Chrome)

```
Uncaught TypeError: f is not a function
    at l.binsNumber (https://code.highcharts.com/modules/histogram-bellcurve.js:13:354)
    at l.setDerivedData (https://code.highcharts.com/modules/histogram-bellcurve.js:12:442)
    at a.Chart.<anonymous> (https://code.highcharts.com/modules/histogram-bellcurve.js:10:78)
    at a.fireEvent (https://code.highcharts.com/highcharts.js:31:242)
    at a.Chart.<anonymous> (https://code.highcharts.com/modules/histogram-bellcurve.js:11:26)
    at a.Chart.a.(anonymous function) [as linkSeries] (https://code.highcharts.com/highcharts.js:19:293)
    at a.Chart.firstRender (https://code.highcharts.com/highcharts.js:256:277)
    at a.Chart.init (https://code.highcharts.com/highcharts.js:232:5)
    at a.Chart.getArgs (https://code.highcharts.com/highcharts.js:230:403)
    at new a.Chart (https://code.highcharts.com/highcharts.js:230:202)
```

#### Live demo with steps to reproduce

http://jsfiddle.net/3drny1k9/1/

#### Affected browser(s)

Firefox and chrome

**Comment by Munksgaard** [comment]
I believe the following code is at fault: https://github.com/highcharts/highcharts/blob/master/js/modules/histogram.src.js#L190-L198

The computed `binsNumber` on line 192 is a boolean (`true` if the argument was a function, false otherwise) and on line 195 it is called as a function.

**Comment by KacperMadej** [comment]
Hi,

Thank you for reporting about the bug and pointing the source of the error.

Another problems:
* number of bins is bigger than the setting by 1
* docs says: `By default it is set to the square of the base series' data length` but should say **square root**

**Comment by KacperMadej** [comment]
The above commit should resolve 2 out of 3 issues: allow functions to be used as the option and fix docs info.

The remaining issue can be resolved by having the last bin right closed.
Would that be a good solution? 
@morganfree
