### ISSUE TITLE
Removing and readding a Series when using boost.js gives exception

### ISSUE THREAD

**Issue by MrLight** [highcharts/highcharts#7540]
#### Expected behaviour
removing and adding series should be possible when using boost.js

#### Actual behaviour
When removing all existing series and then readding some the library gives a error during redraw.
`Uncaught TypeError: Cannot read property 'pos' of undefined
    at a.Chart.b.renderTarget.b.boostResizeTarget (https://code.highcharts.com/modules/boost.js:38:129)
    at ba (https://code.highcharts.com/modules/boost.js:38:434)
    at l.renderCanvas (https://code.highcharts.com/modules/boost.js:57:200)
    at l.c (https://code.highcharts.com/modules/boost.js:50:461)
    at l.a.(anonymous function) [as render] (https://code.highcharts.com/highcharts.js:19:293)
    at l.redraw (https://code.highcharts.com/highcharts.js:296:208)
    at https://code.highcharts.com/highcharts.js:234:431
    at Array.forEach (<anonymous>)
    at a.each (https://code.highcharts.com/highcharts.js:29:80)
    at a.Chart.redraw (https://code.highcharts.com/highcharts.js:234:386)`

This happens since highchart 6. Using highchart 5 the failure was not visible.

#### Live demo with steps to reproduce

http://jsfiddle.net/ozr1mdr2/
--> press readd series

#### Affected browser(s)
IE + Chrome tested

**Comment by MrLight** [comment]
double post same like 7499
