### ISSUE TITLE
Got an error on 'gulp test'

### ISSUE THREAD

**Issue by inuad** [highcharts/highcharts#7938]
I have forked the repo and I would like to add new Indicators series type for the next pulling request. But After I cloned the repo and then I try to run 'gulp test' and then I found some error.

Error's showing as

> HeadlessChrome 64.0.3282 (Windows 8.1.0.0) Highcharts #6537 - 1M button should select range 28.02-31.03 FAILED
>         xAxis minimum correct
>         Expected: "2017-02-28 01:00:00"
>         Actual: "2017-02-28 00:00:00"
>             at Object.<anonymous> (samples/unit-tests/rangeselector/input-range/demo.js:104:12)
>             at runTest (node_modules/qunitjs/qunit/qunit.js:1478:30)
>             at Test.run (node_modules/qunitjs/qunit/qunit.js:1464:6)
>             at node_modules/qunitjs/qunit/qunit.js:1670:12
>             at advance (node_modules/qunitjs/qunit/qunit.js:1116:26)

#### Product version
Highcharts, pulling from master branch.

**Comment by KacperMadej** [comment]
Hi @Nuadnoi 

Thank you for reporting about the problem.
It's not important, but are you by any chance in a different time zone than UTC+1?

_Internal note:_ demo is using depreciated [global useUTC]()https://github.com/highcharts/highcharts/blame/master/samples/unit-tests/rangeselector/input-range/demo.js#L63

**Comment by TorsteinHonsi** [comment]
I also get this error when running the `gulp test --browsers all`, meaning the tests run on BrowserStack machines. It fails for Chrome on Windows, but not on the Mac. I also suspect the time zone to be the problem. 

> Internal note: demo is using depreciated global.useUTC

In principle that's not a problem, but when using `setOptions` in tests we need to make sure they are reset after the assertions, otherwise they will affect subsequent tests. So the safest thing here may be to set `time.useUTC` on the chart instance.

**Comment by sebastianbochan** [comment]
@bre1470 is it still valid in BrowserStack after your recent updates?

**Comment by bre1470** [comment]
My recent updates do not cover changes to BrowserStack and Karma. The results are probably similar to others:
- BS Chrome succeeds in all tests.
- BS Safari succeeds in all tests.
- BS Edge has 2 failing tests and disconnects (1 time problem).
- BS Firefox has 2 (macOS) and 5 (Windows) failing tests (1 time problem).
- BS IE has 10 failing tests regarding test templates.

**Comment by bre1470** [comment]
Situation does not look much better. There are still quite a few issues on Windows browsers. Results with current master:
```
Chrome 76.0.3809 (Mac OS X 10.14.5): Executed 1507 of 1523 (skipped 16) SUCCESS
Chrome 76.0.3809 (Windows 10.0.0): Executed 1507 of 1523 (skipped 16) SUCCESS
Edge 18.18262.0 (Windows 10.0.0): Executed 458 of 1522 (skipped 1) ERROR
Edge 18.18262.0 (Windows 10.0.0) ERROR
Object doesn't support property or method 'setState'
  at code/highcharts.src.js:6172:25
  TypeError: Object doesn't support property or method 'setState'
     at Anonymous function (code/highcharts.src.js:6172:25)
Firefox 68.0.0 (Mac OS X 10.14.0): Executed 1160 of 1522 (skipped 12) SUCCESS
Firefox 68.0.0 (Windows 10.0.0): Executed 1356 of 1522 (1 FAILED)
Firefox 68.0.0 (Windows 10.0.0) labels alignment useHtml: false FAILED
    yAxis label "Category 1" is centered vertically.
        Expected: 244.48332977294922
        Actual: 247.13333129882812
        getTestFunction/<@samples/unit-tests/gantt/grid-axis/demo.js:897:14
        @samples/unit-tests/gantt/grid-axis/demo.js:917:9
        H[key]@code/highcharts.src.js:2196:45
        @samples/unit-tests/gantt/grid-axis/demo.js:916:7
        H[key]@code/highcharts.src.js:2196:45
        @samples/unit-tests/gantt/grid-axis/demo.js:915:5
        runTest@node_modules/qunit/qunit/qunit.js:3041:30
        run@node_modules/qunit/qunit/qunit.js:3027:6
        runTest/<@node_modules/qunit/qunit/qunit.js:3258:12
        processTaskQueue@node_modules/qunit/qunit/qunit.js:2614:24
        processTaskQueue/<@node_modules/qunit/qunit/qunit.js:2618:8
    yAxis label "Category 2" is centered vertically.
        Expected: 163
        Actual: 165.5
        getTestFunction/<@samples/unit-tests/gantt/grid-axis/demo.js:897:14
        @samples/unit-tests/gantt/grid-axis/demo.js:917:9
        H[key]@code/highcharts.src.js:2196:45
        @samples/unit-tests/gantt/grid-axis/demo.js:916:7
        H[key]@code/highcharts.src.js:2196:45
        @samples/unit-tests/gantt/grid-axis/demo.js:915:5
        runTest@node_modules/qunit/qunit/qunit.js:3041:30
        run@node_modules/qunit/qunit/qunit.js:3027:6
        runTest/<@node_modules/qunit/qunit/qunit.js:3258:12
        processTaskQueue@node_modules/qunit/qunit/qunit.js:2614:24
        processTaskQueue/<@node_modules/qunit/qunit/qunit.js:2618:8
    yAxis label "Category 3" is centered vertically.
        Expected: 80.98332977294922
        Actual: 83.83332824707031
        getTestFunction/<@samples/unit-tests/gantt/grid-axis/demo.js:897:14
        @samples/unit-tests/gantt/grid-axis/demo.js:917:9
        H[key]@code/highcharts.src.js:2196:45
        @samples/unit-tests/gantt/grid-axis/demo.js:916:7
        H[key]@code/highcharts.src.js:2196:45
        @samples/unit-tests/gantt/grid-axis/demo.js:915:5
        runTest@node_modules/qunit/qunit/qunit.js:3041:30
        run@node_modules/qunit/qunit/qunit.js:3027:6
        runTest/<@node_modules/qunit/qunit/qunit.js:3258:12
        processTaskQueue@node_modules/qunit/qunit/qunit.js:2614:24
        processTaskQueue/<@node_modules/qunit/qunit/qunit.js:2618:8
    yAxis label "Category 1<br/>Second Line" is centered vertically.
        Expected: 220
        Actual: 222.5
        getTestFunction/<@samples/unit-tests/gantt/grid-axis/demo.js:897:14
        @samples/unit-tests/gantt/grid-axis/demo.js:933:9
        H[key]@code/highcharts.src.js:2196:45
        @samples/unit-tests/gantt/grid-axis/demo.js:932:7
        H[key]@code/highcharts.src.js:2196:45
        @samples/unit-tests/gantt/grid-axis/demo.js:931:5
        runTest@node_modules/qunit/qunit/qunit.js:3041:30
        run@node_modules/qunit/qunit/qunit.js:3027:6
        runTest/<@node_modules/qunit/qunit/qunit.js:3258:12
        processTaskQueue@node_modules/qunit/qunit/qunit.js:2614:24
        processTaskQueue/<@node_modules/qunit/qunit/qunit.js:2618:8
    yAxis label "Category 2<br/>Second Line" is centered vertically.
        Expected: 145
        Actual: 147.5
        getTestFunction/<@samples/unit-tests/gantt/grid-axis/demo.js:897:14
        @samples/unit-tests/gantt/grid-axis/demo.js:933:9
        H[key]@code/highcharts.src.js:2196:45
        @samples/unit-tests/gantt/grid-axis/demo.js:932:7
        H[key]@code/highcharts.src.js:2196:45
        @samples/unit-tests/gantt/grid-axis/demo.js:931:5
        runTest@node_modules/qunit/qunit/qunit.js:3041:30
        run@node_modules/qunit/qunit/qunit.js:3027:6
        runTest/<@node_modules/qunit/qunit/qunit.js:3258:12
        processTaskQueue@node_modules/qunit/qunit/qunit.js:2614:24
        processTaskQueue/<@node_modules/qunit/qunit/qunit.js:2618:8
    yAxis label "Category 3<br/>Second Line" is centered vertically.
        Expected: 69.5
        Actual: 72.5
        getTestFunction/<@samples/unit-tests/gantt/grid-axis/demo.js:897:14
        @samples/unit-tests/gantt/grid-axis/demo.js:933:9
        H[key]@code/highcharts.src.js:2196:45
        @samples/unit-tests/gantt/grid-axis/demo.js:932:7
        H[key]@code/highcharts.src.js:2196:45
        @samples/unit-tests/gantt/grid-axis/demo.js:931:5
        runTest@node_modules/qunit/qunit/qunit.js:3041:30
        run@node_modules/qunit/qunit/qunit.js:3027:6
        runTest/<@node_modules/qunit/qunit/qunit.js:3258:12
        processTaskQueue@node_modules/qunit/qunit/qunit.js:2614:24
        processTaskQueue/<@node_modules/qunit/qunit/qunit.js:2618:8
IE 11.0.0 (Windows 10.0.0): Executed 358 of 1522 (3 FAILED) (skipped 1) ERROR
IE 11.0.0 (Windows 10.0.0) Highcharts 3D columns dataLabels initial visibility FAILED
        Died on test #1 undefined: Unable to get property 'length' of undefined or null reference
        TypeError: Unable to get property 'length' of undefined or null reference
           at Anonymous function (samples/unit-tests/3d/column-data-labels-visibility/demo.js:33:3)
           at runTest (node_modules/qunit/qunit/qunit.js:3041:6)
           at run (node_modules/qunit/qunit/qunit.js:3027:6)
           at Anonymous function (node_modules/qunit/qunit/qunit.js:3258:7)
           at processTaskQueue (node_modules/qunit/qunit/qunit.js:2614:6)
           at Anonymous function (node_modules/qunit/qunit/qunit.js:2618:8)
           at invokeCallback (node_modules/qunit/qunit/qunit.js:1699:9)
           at Anonymous function (node_modules/qunit/qunit/qunit.js:1467:9)
           at flush (node_modules/qunit/qunit/qunit.js:1419:7)
IE 11.0.0 (Windows 10.0.0) Highcharts Update from 2D to 3D stacked columns FAILED
        Died on test #1 undefined: Unable to get property 'length' of undefined or null reference
        TypeError: Unable to get property 'length' of undefined or null reference
           at Anonymous function (samples/unit-tests/3d/column-stacked-3d-update/demo.js:48:3)
           at runTest (node_modules/qunit/qunit/qunit.js:3041:6)
           at run (node_modules/qunit/qunit/qunit.js:3027:6)
           at Anonymous function (node_modules/qunit/qunit/qunit.js:3258:7)
           at processTaskQueue (node_modules/qunit/qunit/qunit.js:2614:6)
           at Anonymous function (node_modules/qunit/qunit/qunit.js:2618:8)
           at invokeCallback (node_modules/qunit/qunit/qunit.js:1699:9)
           at Anonymous function (node_modules/qunit/qunit/qunit.js:1467:9)
           at flush (node_modules/qunit/qunit/qunit.js:1419:7)
IE 11.0.0 (Windows 10.0.0) Highcharts #3165 - Stack labels in waterfall series FAILED
        The y attribute is equal to 0.
        Expected: 0
        Actual: -3.059999942779541
           at Anonymous function (samples/unit-tests/axis/waterfall-stacklabels/demo.js:52:3)
           at runTest (node_modules/qunit/qunit/qunit.js:3041:6)
           at run (node_modules/qunit/qunit/qunit.js:3027:6)
           at Anonymous function (node_modules/qunit/qunit/qunit.js:3258:7)
           at processTaskQueue (node_modules/qunit/qunit/qunit.js:2614:6)
           at Anonymous function (node_modules/qunit/qunit/qunit.js:2618:8)
IE 11.0.0 (Windows 10.0.0) ERROR
  Object doesn't support property or method 'setState'
  at code/highcharts.src.js:6172:25
  TypeError: Object doesn't support property or method 'setState'
     at Anonymous function (code/highcharts.src.js:6172:25)
Safari 12.1.1 (Mac OS X 10.14.5): Executed 1514 of 1523 (skipped 9) SUCCESS
```

**Comment by TorsteinHonsi** [comment]
We abandoned Edge and IE11 on Circle because of stability problems, so unfortunately the CI will not capture this stuff. Plus Edge will soon make the switch to Webkit. FYI @activist.

**Comment by activist** [comment]
A part from the disconnects on Edge we could potentially add more browser tests in the CI pipeline, but in terms of build time I don't think we should increase it more than it already is. So if we were to do this it would require that we add more instances on Browserstack or evaluate alternatives like Lambdatest which is about half of the price.

Edge on Chromium is scheduled for release on 2020-01-15 (it is possible to run the preview on BS).
