### ISSUE TITLE
Cannot load any modules

### ISSUE THREAD

**Issue by stevendesu** [highcharts/highcharts#9041]
I installed the latest version of HighCharts via NPM:

```
$> npm install highcharts
```

#### Expected behaviour

```
$> node
> const Highcharts = require("highcharts");
undefined
> require("highcharts/modules/stock")(Highcharts);
undefined
> require("highcharts/modules/map")(Highcharts);
undefined
> require("highcharts/modules/drilldown")(Highcharts);
undefined
> require("highcharts/modules/solid-gauge")(Highcharts);
undefined
>
```

#### Actual behaviour

```
$> node
> const Highcharts = require("highcharts");
undefined
> require("highcharts/modules/stock")(Highcharts);
TypeError: Cannot read property 'prototype' of undefined
    at /home/sbarnett/src/node_modules/highcharts/modules/stock.js:9:309
    at /home/sbarnett/src/node_modules/highcharts/modules/stock.js:20:434
> require("highcharts/modules/map")(Highcharts);
TypeError: m is not a function
    at /home/sbarnett/src/node_modules/highcharts/modules/map.js:9:225
    at /home/sbarnett/src/node_modules/highcharts/modules/map.js:11:289
> require("highcharts/modules/drilldown")(Highcharts);
TypeError: Cannot read property 'pie' of undefined
    at /home/sbarnett/src/node_modules/highcharts/modules/drilldown.js:9:323
    at /home/sbarnett/src/node_modules/highcharts/modules/drilldown.js:27:227
> require("highcharts/modules/solid-gauge")(Highcharts);
TypeError: Cannot read property 'prototype' of undefined
    at /home/sbarnett/src/node_modules/highcharts/modules/solid-gauge.js:9:249
    at /home/sbarnett/src/node_modules/highcharts/modules/solid-gauge.js:14:368
>
```

#### Live demo with steps to reproduce

**[The template](https://jsfiddle.net/highcharts/llexl/) threw a 404**

I'm trying to build my app with WebPack so I'm not loading HighCharts via a `<script>` tag. See "Actual Behavior" above for live repro steps in Node.

#### Product version

**6.1.3**

#### Affected browser(s)

All of them

**Comment by stevendesu** [comment]
@KacperMadej 

Thank you for the links. Using jsdom() I was able to get my code above to work, proving the issue didn't lie with Highcharts but with my implementation in WebPack. This caused me to dig deeper and I eventually figured it out.

My WebPack config was canonicalizing module names to the root of my "src" directory. So the file `my-app/src/components/list.js` could be referenced using simply: `import List from "components/list";`

I was initializing HighCharts like so (it was a VueJS app):

***index.js***
```js
// ...
require("./highcharts");
// ...
```

***highcharts.js***
```js
var Vue = require("vue");
var VueHighcharts = require("vue-highcharts");
var Highcharts = require("highcharts");
require("highcharts/modules/stock")(Highcharts);
Vue.use(VueHighcharts, { Highcharts: Highcharts });
```

This was throwing an error on line 4 of `highcharts.js` when I attempted to import the module. What I didn't realize is that on line 3 the `var Highcharts = require("highcharts");` line was ***not*** including Highcharts from node_modules. It was requiring itself, recursively, which apparently returns `undefined`.
