### ISSUE TITLE
TypeError: z.getSpanWidth is not a function after last update

### ISSUE THREAD

**Issue by leopold537** [highcharts/highcharts#9058]
#### Expected behaviour
Highcharts doesn't throw an error

#### Actual behaviour
Highcharts thows an error.

#### Config
`    {"colors":["#f48639","#929039","#d63859","#5cc6d4","#224088","#cb4039","#3d9aa9"],"chart":{"zoomType":"x"},"xAxis":{"crosshair":true,"title":{"text":null},"labels":{"enabled":true},"tickInterval":null,"min":null,"max":null,"categories":null},"series":[{"name":"B","type":"line","data":[[5,7208],[7,5569],[15,5884],[18,5742],[23,5317],[31,7746],[33,9346],[34,9049],[35,7488],[40,7864],[45,7564],[46,9094],[47,5854],[49,6733],[57,6568],[58,6668],[60,9026],[70,5481],[75,5436],[79,9106],[82,7773],[86,8729],[88,6803],[97,8167],[98,5811],[103,7042],[107,7928],[110,8572],[113,7156],[114,4924],[115,9790],[124,9880],[131,5390],[133,8846],[137,7445],[139,6890],[142,8286],[143,7073],[144,8339],[145,7894],[149,9346],[150,9095],[155,7376],[160,5512],[164,6353],[166,8090],[168,8093],[172,5571],[174,5094],[175,5091],[188,5678],[199,8145],[204,6700],[206,9785],[216,9469],[222,5545],[226,6777],[230,6146],[231,9717],[234,7247],[237,8323],[257,6920],[258,5976],[261,6649],[266,6851],[269,7419],[276,9181],[279,7533],[281,7838],[283,7537],[285,6366],[290,6387],[296,6181],[302,5127],[303,8523],[304,4941],[307,9830],[311,7263],[313,5402],[315,4897],[319,5108],[320,6951],[325,9604],[326,9358],[327,8029],[328,8035],[333,6134],[335,9004],[336,5593],[338,8134],[342,7678],[345,5722],[347,6211],[352,9620],[357,5443],[361,5384],[365,7310],[367,6755],[370,6609],[373,8521],[380,8041],[385,6095],[389,6093],[391,8807],[392,7003],[400,8238],[406,7736],[408,9483],[413,6978],[414,9500],[425,7787],[428,9163],[429,6282],[431,6607],[432,6399],[438,8256],[443,6101],[444,5024],[447,5506],[451,7569],[464,8617],[472,9549],[475,9076],[490,4995],[492,9422],[496,9502],[500,9022],[504,6100],[511,7775],[515,8252],[516,8620],[518,8503],[522,8227],[524,6640],[533,5208],[534,4898],[536,5326],[548,8444],[549,9914],[552,7941],[553,8705],[555,6851],[558,7549],[565,6639],[568,7083],[569,6906],[578,5212],[581,7099],[583,9890],[591,6757],[594,8398],[595,7924],[598,6232],[601,9223],[609,7761],[613,6616],[614,5100],[617,8578],[619,6579],[620,9845],[626,7570],[628,6758],[632,6381],[634,9165],[640,8014],[644,9998],[645,6452],[647,5564],[651,8285],[654,9006],[655,9648],[657,8411],[660,5584],[664,6015],[665,9950],[666,6884],[674,9620],[676,8767],[677,6995],[682,6223],[689,8326],[698,8774],[701,6703],[705,9985],[709,7781],[714,8623],[715,9230],[720,6934],[723,5644],[736,7915],[738,4950],[742,8230],[744,9607],[745,8347],[746,6245],[747,7400],[758,7623],[761,6935],[763,6948],[774,9271],[786,8099],[787,5323],[791,5277],[793,6356],[794,9821],[799,9732],[802,7217],[805,9240],[811,5196],[816,9598],[817,7148],[818,5110],[820,5008],[832,9770],[833,5932],[841,8753],[842,6244],[843,6994],[844,7887],[848,5927],[853,6482],[857,8531],[861,7225],[867,6938],[873,7520],[875,6830],[877,6788],[879,5919],[883,8097],[887,6503],[895,7857],[896,9827],[897,8606],[907,9878],[911,7307],[913,6868],[915,5337],[916,8811],[918,8398],[920,5252],[922,7598],[923,7569],[924,4934],[925,7135],[927,5558],[929,9188],[934,8537],[939,5646],[946,8899],[947,7790],[948,7856],[949,7635],[951,9699],[957,8551],[958,6507],[962,8096],[963,6459],[966,7731],[979,9353],[982,7700],[985,4905],[991,5761],[1001,6952],[1004,7250],[1006,6226],[1010,4973],[1014,8088],[1019,5295],[1021,9282],[1035,6884],[1040,7553],[1043,8063],[1050,5931],[1052,6893],[1060,8996],[1065,5167],[1069,5562],[1072,9640],[1074,7285],[1077,8549],[1082,7564],[1089,9843],[1094,6888],[1098,6757],[1106,5409],[1118,4908],[1120,9913],[1123,8271],[1125,5768],[1126,7215],[1137,6304],[1140,7532],[1142,5408],[1148,5798],[1152,9850],[1153,7387],[1182,9203],[1185,5006],[1187,9570],[1189,9309],[1190,8085],[1191,9353],[1194,6358],[1197,5509],[1199,8810],[1205,9579],[1209,8610],[1210,8046],[1218,5754],[1219,8694],[1220,9230],[1222,7504],[1223,5903],[1232,5075],[1233,5981],[1235,9851],[1247,5740],[1248,6123],[1250,6014],[1252,5074],[1254,7733],[1257,8565],[1260,7353],[1261,8520],[1265,8796],[1266,9989],[1268,8968],[1271,8168],[1273,8216],[1275,5447],[1280,9551],[1289,7646],[1292,9479],[1295,9988],[1297,7014],[1299,6616],[1306,7191],[1308,6551],[1313,7884],[1314,6602],[1318,5517],[1322,7770],[1325,9989],[1331,9393],[1333,9781],[1334,8488],[1345,5439],[1347,9988],[1350,6582],[1354,7449],[1356,6636],[1357,6534],[1360,7697],[1365,8221],[1368,6494],[1371,5233],[1380,8610],[1381,4989],[1385,9329],[1389,7892],[1392,5960],[1393,8624],[1395,5372],[1411,6728],[1413,9206],[1426,8072],[1432,8669],[1434,9929],[1438,6268],[1439,7698],[1450,9408],[1453,5300],[1460,6009],[1461,8380],[1469,9343],[1471,8014],[1478,9276],[1479,9690],[1482,6980],[1483,6363],[1484,8342],[1487,5592],[1492,5677],[1494,6763],[1505,5720],[1509,5006],[1515,6923],[1522,5921],[1523,8666],[1526,7427],[1534,7095],[1547,6364],[1552,5379],[1553,8341],[1554,7434],[1556,6559],[1558,5956],[1562,6920],[1564,9075],[1567,5126],[1571,6792],[1572,6315],[1574,8455],[1579,5737],[1583,7343],[1584,7205],[1585,9167],[1588,9052],[1589,9557],[1597,6848],[1604,7959],[1608,9841],[1610,9008],[1615,6314],[1622,5417],[1630,6392],[1635,7156],[1643,6250],[1646,8460],[1649,9648],[1666,6999],[1667,9038],[1671,9187],[1672,6487],[1674,8469],[1675,9677],[1684,7117],[1687,5616],[1688,8884],[1694,7918],[1702,5888],[1708,9947],[1710,8975],[1714,8797],[1715,8337],[1722,6644],[1726,7383],[1731,8589],[1737,6839],[1742,8592],[1750,7606],[1752,5056],[1753,7503],[1754,7139],[1759,7439],[1761,7770],[1765,6038],[1781,6195],[1786,7398],[1788,6101],[1797,9859],[1811,9538],[1819,8698],[1820,8476],[1823,8006],[1827,5158],[1832,8264],[1834,5735],[1836,6803],[1847,9585],[1848,8422],[1849,6249],[1850,8417],[1851,7092],[1855,10000],[1857,8502],[1858,6205],[1869,9776],[1873,9940],[1887,5570],[1889,6982],[1891,7861],[1893,5893],[1895,5304],[1897,8853],[1898,7677],[1906,8558],[1912,7630],[1915,9822],[1920,8890],[1921,8742],[1923,9298],[1925,7851],[1927,8946],[1931,8024],[1936,5163],[1938,5073],[1941,9050],[1947,4953],[1948,7386],[1949,7484],[1950,6099],[1955,9779],[1961,5530],[1962,5701],[1968,9447],[1969,9835],[1971,9423],[1972,7009],[1973,8969]],"color":null,"yAxis":0,"regression":null,"marker":{"symbol":"circle","radius":1,"lineColor":null,"lineWidth":2}}],"plotOptions":{"series":{"dataLabels":{"enabled":false,"align":"center","allowOverlap":false}},"pie":{"dataLabels":{"enabled":true}}},"title":{"text":"Graph Title"},"tooltip":{"shared":true,"enabled":true},"credits":{"enabled":false},"exporting":{"filename":"graph-title","enabled":true,"buttons":{"contextButton":{"x":-15}},"chartOptions":{"legend":{"adjustChartSize":true,"navigation":{"enabled":false}}}},"legend":{"enabled":true},"yAxis":[{"crosshair":true,"title":{"text":null},"labels":{"enabled":true},"tickInterval":null,"min":null,"max":null,"opposite":false}]}
`

#### Stack Trace
      
      at getSpanWidth (node_modules/highcharts/highcharts.src.js:5744:31)
      at a.SVGRenderer.getSubStringLength [as truncate] (node_modules/highcharts/highcharts.src.js:5753:25)
      at truncate (node_modules/highcharts/highcharts.src.js:6143:43)
          at Array.forEach (<anonymous>)
      at call (node_modules/highcharts/highcharts.src.js:2270:14)
      at each (node_modules/highcharts/highcharts.src.js:5981:19)
          at Array.forEach (<anonymous>)
      at call (node_modules/highcharts/highcharts.src.js:2270:14)
      at a.SVGRenderer.each [as buildText] (node_modules/highcharts/highcharts.src.js:5969:15)
      at a.SVGElement.buildText [as css] (node_modules/highcharts/highcharts.src.js:4137:23)
      at a.Chart.css (node_modules/highcharts/highcharts.src.js:26292:19)
          at Array.forEach (<anonymous>)
      at call (node_modules/highcharts/highcharts.src.js:2270:14)
      at a.Chart.each [as layOutTitles] (node_modules/highcharts/highcharts.src.js:26279:11)
      at a.Chart.layOutTitles [as setTitle] (node_modules/highcharts/highcharts.src.js:26259:11)
      at a.Chart.setTitle [as render] (node_modules/highcharts/highcharts.src.js:27303:11)
      at a.Chart.render [as firstRender] (node_modules/highcharts/highcharts.src.js:27588:11)
      at a.Chart.firstRender (node_modules/highcharts/highcharts.src.js:25734:15)
      at call (node_modules/highcharts/highcharts.src.js:2533:11)
      at a.Chart.fireEvent (node_modules/highcharts/highcharts.src.js:25607:11)
      at a.Chart.apply (src/common/highcharts/Regression.js:101:13)
      at a.Chart.apply [as init] (node_modules/highcharts/highcharts.src.js:1394:17)
      at a.Chart.init [as getArgs] (node_modules/highcharts/highcharts.src.js:25578:11)
      at new apply (node_modules/highcharts/highcharts.src.js:25498:7)
      at n.value (node_modules/react-highcharts/ReactHighcharts.js:1:2490)
      at n.value (node_modules/react-highcharts/ReactHighcharts.js:1:3078)
      at node_modules/react-dom/lib/ReactCompositeComponent.js:262:25
      at measureLifeCyclePerf (node_modules/react-dom/lib/ReactCompositeComponent.js:73:12)
      at node_modules/react-dom/lib/ReactCompositeComponent.js:261:11
      at CallbackQueue.notifyAll (node_modules/react-dom/lib/CallbackQueue.js:74:22)
      at ReactReconcileTransaction.close (node_modules/react-dom/lib/ReactReconcileTransaction.js:78:26)
      at ReactReconcileTransaction.closeAll (node_modules/react-dom/lib/Transaction.js:207:25)
      at ReactReconcileTransaction.perform (node_modules/react-dom/lib/Transaction.js:154:16)
      at batchedMountComponentIntoNode (node_modules/react-dom/lib/ReactMount.js:124:15)
      at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-dom/lib/Transaction.js:141:20)
      at Object.batchedUpdates (node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:60:26)
      at Object.batchedUpdates (node_modules/react-dom/lib/ReactUpdates.js:95:27)
      at Object._renderNewRootComponent (node_modules/react-dom/lib/ReactMount.js:317:18)
      at Object._renderSubtreeIntoContainer (node_modules/react-dom/lib/ReactMount.js:399:32)
      at Object.render (node_modules/react-dom/lib/ReactMount.js:420:23)
      at Object.render (node_modules/enzyme-adapter-react-15/build/ReactFifteenAdapter.js:186:50)
      at new ReactWrapper (node_modules/enzyme/build/ReactWrapper.js:119:16)
      at mount (node_modules/enzyme/build/mount.js:21:10)
      at Object.<anonymous> (src/common/components/editors/graph/__tests__/Series.test.jsx:11:21)`

#### Product version
6.1.4

#### Affected browser(s)
Chrome 69

**Comment by sebastianbochan** [comment]
Hi @leopold537,
Thank you for contacting us. When I replicate your example as live demo here: https://jsfiddle.net/BlackLabel/nqeohL7z/ all seems to working fine. In your error-log, I see references to react. Could you confirm that you use our official react wrapper or different? Are you able to reproduce your example as simplified live demo? It will allow us to debug it further.

**Comment by kris-ellery** [comment]
Getting the same error. `6.1.3` works, `6.1.4` breaks with `TypeError: z.getSpanWidth is not a function` error.

**Comment by denchen** [comment]
Weirdly enough, I'm only getting this error in testing (Create React App + Jest). When I'm running my application in dev mode, all charts render fine. I'm on `highcharts@6.1.4` & `react-highcharts@16.0.2`

Pinning to `highcharts@6.1.3` resolves my test issues.

**Comment by TorsteinHonsi** [comment]
First, make sure that all Highcharts files are on the same version so you don't have old module files on top of the latest highcharts.js.

Some background information. The `getSpanWidth` was removed in v6.1.4 as part of a refactoring to increase performance of text rendering (see #5009). It remains however in oldIE. It is referenced once from the highcharts.js file, [see this line](https://github.com/highcharts/highcharts/blob/v6.1.4/js/parts/SvgRenderer.js#L2845). This is inside a condition where we first check for `tspan.getSubStringLength`, and if that is falsy, we use `getSpanWidth`. The idea is that `tspan.getSubStringLength` is a function in all SVG capable browsers, so only oldIE should revert to `getSpanWidth`.

**Comment by denchen** [comment]
Okay, I get what you're saying that `getSpanWidth()` is only called if `tspan.getSubStringLength` is false, but you [removed the actual `getSpanWidth()` function in this commit](https://github.com/highcharts/highcharts/commit/6c5668985634b3ccdd5bea4ccdd363b02fd46a0d). So doesn't that mean that code path will always fail?

**Comment by TorsteinHonsi** [comment]
> So doesn't that mean that code path will always fail?

It fails for IE8 and older, but those browsers require `modules/oldie.js` to render charts in the first place. And when `oldie.js` is loaded, `getSpanWidth` is defined. We could do more checks, but it only confirms what we know, that SVG charts won't render in IE8.

Unless it is an actual bug, a use case where this error is thrown in anything else than IE6-8. So it would be great if you are able to reproduce that, then we would what happens, why `tspan.getSubStringLength` is falsy etc.

**Comment by denchen** [comment]
Hi @TorsteinHonsi ,

I have a [Git repo that reproduces the testing bug I'm seeing](https://github.com/denchen/highcharts-bug).

The application and chart renders just fine in the browser; it's only during tests that it fails. Reproduce simply by running `yarn test`

**Comment by TorsteinHonsi** [comment]
Okay so your tests are running jsdom? That may explain why `tspan.getSubStringLength` is not available. It's not fully capable at SVG.

**Comment by dpgalloway** [comment]
Running into the same exact issue. Also very interested in any workaround as we'd like to test our components that use Highcharts.

**Comment by kishoremvrs** [comment]
> 
> 
> This issue was fixed in Highcharts v6.2.0. @dpgalloway what version are you running?

I am using highcharts version 5.0.11? Unfortunately i can't upgrade to 6.2.0

Is there a workaround for this?

**Comment by pawelfus** [comment]
Hi @kishoremvrs 

You can edit source code, the fix is rather simple, please take a look: adb846026a0590cfa6872e88c59ee30226f6d8cb
