### ISSUE TITLE
Generate API Docs error: Cannot find module 'highcharts-api-doc-gen'

### ISSUE THREAD

**Issue by camsteffen** [highcharts/highcharts#9927]
I tried to follow the instructions in the readme to generate API docs for version 6.1.1. I checked out the tag for that version. I cloned api-docs and highcharts-docstrap at master next to highcharts. Ran `npm -i` in all 3. When I run `gulp jsdoc --watch` I get the following error. What am I doing wrong?

```
[11:47:32] Error: Cannot find module 'highcharts-api-doc-gen'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Promise (/Users/csteffen/Developer/highcharts-parent/highcharts/gulpfile.js:854:22)
    at Promise (<anonymous>)
    at generateAPI (/Users/csteffen/Developer/highcharts-parent/highcharts/gulpfile.js:853:58)
    at Promise.then (/Users/csteffen/Developer/highcharts-parent/highcharts/gulpfile.js:935:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7
```

**Comment by camsteffen** [comment]
Got it. I had to change the `"name"` of the package in api-docs/package.json from `"highcharts-api-docs"` to `"highcharts-api-doc-gen"`
